--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 3/09/2021 11:50:47 PM
-- Server version: 8.0.26
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `misa.amis_accountant.mf938`;

--
-- Drop procedure `Proc_GetEmployees`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployees;

--
-- Drop procedure `Proc_GetFilterPagingEmployees`
--
DROP PROCEDURE IF EXISTS Proc_GetFilterPagingEmployees;

--
-- Drop view `view_employees`
--
DROP VIEW IF EXISTS view_employees CASCADE;

--
-- Drop procedure `Proc_DeleteEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteEmployeeById;

--
-- Drop procedure `Proc_GetEmployeeById`
--
DROP PROCEDURE IF EXISTS Proc_GetEmployeeById;

--
-- Drop procedure `Proc_GetNewEmployeeCode`
--
DROP PROCEDURE IF EXISTS Proc_GetNewEmployeeCode;

--
-- Drop procedure `Proc_InsertEmployee`
--
DROP PROCEDURE IF EXISTS Proc_InsertEmployee;

--
-- Drop procedure `Proc_UpdateEmployee`
--
DROP PROCEDURE IF EXISTS Proc_UpdateEmployee;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop procedure `Proc_DeleteUnitById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteUnitById;

--
-- Drop procedure `Proc_GetUnits`
--
DROP PROCEDURE IF EXISTS Proc_GetUnits;

--
-- Drop table `unit`
--
DROP TABLE IF EXISTS unit;

--
-- Set default database
--
USE `misa.amis_accountant.mf938`;

--
-- Create table `unit`
--
CREATE TABLE unit (
  UnitId char(36) NOT NULL DEFAULT '''''' COMMENT 'Id đơn vị',
  UnitCode varchar(20) NOT NULL DEFAULT '''''',
  UnitName varchar(255) NOT NULL DEFAULT '''''',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (UnitId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Đơn vị của nhân viên';

DELIMITER $$

--
-- Create procedure `Proc_GetUnits`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_GetUnits ()
BEGIN
  SELECT
    *
  FROM unit u;
END
$$

--
-- Create procedure `Proc_DeleteUnitById`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_DeleteUnitById (IN UnitId char(36))
BEGIN
  DELETE
    FROM unit
  WHERE unit.UnitId = UnitId;
END
$$

DELIMITER ;

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeId char(36) NOT NULL DEFAULT '''''' COMMENT 'Id nhân viên',
  EmployeeCode varchar(20) NOT NULL DEFAULT '''''' COMMENT 'Mã nhân viên',
  FullName varchar(100) NOT NULL DEFAULT '''''' COMMENT 'Họ và tên',
  DateOfBirth date DEFAULT NULL COMMENT 'Ngày sinh',
  Gender int DEFAULT NULL COMMENT 'Giới tính: 0=nữ; 1=nam; 2= không xác định',
  UnitId char(36) NOT NULL DEFAULT '' COMMENT 'Id đơn vị',
  IdentityNumber varchar(25) DEFAULT NULL COMMENT 'Số CMND',
  IdentityDate date DEFAULT NULL COMMENT 'Ngày cấp CMND',
  IdentityPlace varchar(255) DEFAULT NULL COMMENT 'Nơi cấp CMND',
  Position varchar(100) DEFAULT NULL COMMENT 'Chức danh',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ',
  MobilePhone varchar(50) DEFAULT NULL COMMENT 'Số điện thoại di động',
  DesktopPhone varchar(50) DEFAULT NULL COMMENT 'Số điện thoại để bàn',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  BankAccount varchar(25) DEFAULT NULL COMMENT 'Số tài khoản ngân hàng',
  BankName varchar(255) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankBranch varchar(255) DEFAULT NULL COMMENT 'Chi nhánh ngân hàng',
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(100) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (EmployeeId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 639,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Danh sách nhân viên';

--
-- Create foreign key
--
ALTER TABLE employee
ADD CONSTRAINT FK_employee_UnitId FOREIGN KEY (UnitId)
REFERENCES unit (UnitId);

DELIMITER $$

--
-- Create procedure `Proc_UpdateEmployee`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_UpdateEmployee (IN EmployeeId char(36), IN EmployeeCode varchar(20), IN FullName varchar(100), IN DateOfBirth date, IN Gender int, IN UnitId char(36), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN Position varchar(100), IN Address varchar(255), IN MobilePhone varchar(50), IN DesktopPhone varchar(50), IN Email varchar(100), IN BankAccount varchar(25), IN BankName varchar(255), IN BankBranch varchar(255), IN ModifiedBy varchar(100))
BEGIN
  UPDATE employee e
  SET e.EmployeeCode = EmployeeCode,
      e.FullName = FullName,
      e.DateOfBirth = DateOfBirth,
      e.Gender = Gender,
      e.UnitId = UnitId,
      e.IdentityNumber = IdentityNumber,
      e.IdentityDate = IdentityDate,
      e.IdentityPlace = IdentityPlace,
      e.Position = Position,
      e.Address = Address,
      e.MobilePhone = MobilePhone,
      e.DesktopPhone = DesktopPhone,
      e.Email = Email,
      e.BankAccount = BankAccount,
      e.BankName = BankName,
      e.BankBranch = BankBranch,
      e.ModifiedDate = CURRENT_TIMESTAMP(),
      e.ModifiedBy = ModifiedBy
  WHERE e.EmployeeId = EmployeeId;
END
$$

--
-- Create procedure `Proc_InsertEmployee`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_InsertEmployee (IN EmployeeCode varchar(20), IN FullName varchar(100), IN DateOfBirth date, IN Gender int, IN UnitId char(36), IN IdentityNumber varchar(25), IN IdentityDate date, IN IdentityPlace varchar(255), IN Position varchar(100), IN Address varchar(255), IN MobilePhone varchar(50), IN DesktopPhone varchar(50), IN Email varchar(100), IN BankAccount varchar(25), IN BankName varchar(255), IN BankBranch varchar(255), IN CreatedBy varchar(100))
BEGIN
  INSERT INTO employee (EmployeeId, EmployeeCode, FullName, DateOfBirth, Gender, UnitId, IdentityNumber, IdentityDate, IdentityPlace, Position, Address, MobilePhone, DesktopPhone, Email, BankAccount, BankName, BankBranch, CreatedDate, CreatedBy)
    VALUES (UUID(), EmployeeCode, FullName, DateOfBirth, Gender, UnitId, IdentityNumber, IdentityDate, IdentityPlace, Position, Address, MobilePhone, DesktopPhone, Email, BankAccount, BankName, BankBranch, CURRENT_TIMESTAMP(), CreatedBy);
END
$$

--
-- Create procedure `Proc_GetNewEmployeeCode`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_GetNewEmployeeCode ()
BEGIN
  SELECT
    CONCAT('NV-', (1 + CAST(REPLACE(e.EmployeeCode, 'NV-', '') AS decimal))) AS NewCode
  FROM employee e
  ORDER BY (CAST(REPLACE(e.EmployeeCode, 'NV-', '') AS decimal)) DESC LIMIT 0, 1;
END
$$

--
-- Create procedure `Proc_GetEmployeeById`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_GetEmployeeById (IN EmployeeId char(36))
BEGIN
  SELECT
    *
  FROM employee e
  WHERE e.EmployeeId = EmployeeId;
END
$$

--
-- Create procedure `Proc_DeleteEmployeeById`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_DeleteEmployeeById (IN EmployeeId char(36))
COMMENT 'Xóa một nhân viên theo id'
BEGIN
  DELETE
    FROM employee
  WHERE employee.EmployeeId = EmployeeId;
END
$$

DELIMITER ;

--
-- Create view `view_employees`
--
CREATE
DEFINER = 'hieunv'@'%'
VIEW view_employees
AS
SELECT
  `e`.`EmployeeId` AS `EmployeeId`,
  `e`.`EmployeeCode` AS `EmployeeCode`,
  `e`.`FullName` AS `FullName`,
  `e`.`DateOfBirth` AS `DateOfBirth`,
  `e`.`Gender` AS `Gender`,
  `e`.`IdentityNumber` AS `IdentityNumber`,
  `e`.`IdentityDate` AS `IdentityDate`,
  `e`.`IdentityPlace` AS `IdentityPlace`,
  `e`.`Position` AS `Position`,
  `e`.`Address` AS `Address`,
  `e`.`MobilePhone` AS `MobilePhone`,
  `e`.`DesktopPhone` AS `DesktopPhone`,
  `e`.`Email` AS `Email`,
  `e`.`BankAccount` AS `BankAccount`,
  `e`.`BankName` AS `BankName`,
  `e`.`BankBranch` AS `BankBranch`,
  `e`.`CreatedDate` AS `CreatedDate`,
  `e`.`CreatedBy` AS `CreatedBy`,
  `e`.`ModifiedDate` AS `ModifiedDate`,
  `e`.`ModifiedBy` AS `ModifiedBy`,
  `u`.`UnitId` AS `UnitId`,
  `u`.`UnitName` AS `UnitName`
FROM (`employee` `e`
  LEFT JOIN `unit` `u`
    ON ((`e`.`UnitId` = `u`.`UnitId`)))
ORDER BY CAST(REPLACE(`e`.`EmployeeCode`, 'NV-', '') AS decimal(10, 0)) DESC;

DELIMITER $$

--
-- Create procedure `Proc_GetFilterPagingEmployees`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_GetFilterPagingEmployees (IN PageSize int, IN PageNumber int, IN SearchTerms varchar(100), OUT TotalRecord int)
BEGIN
  DECLARE StartIndex int DEFAULT 0;
  SET @SearchTerms = SearchTerms;
  DROP TEMPORARY TABLE IF EXISTS tmpTable;
  IF PageSize > 0 THEN
    CREATE TEMPORARY TABLE tmpTable AS (SELECT
        *
      FROM view_employees ve
      WHERE 1 = 1
      AND (
      (
      (
      ve.EmployeeCode LIKE CONCAT('%', @SearchTerms, '%')
      OR ve.FullName LIKE CONCAT('%', @SearchTerms, '%')
      OR ve.MobilePhone LIKE CONCAT('%', @SearchTerms, '%')
      OR ve.DesktopPhone LIKE CONCAT('%', @SearchTerms, '%')
      )
      AND @SearchTerms IS NOT NULL
      )
      OR @SearchTerms IS NULL
      ));

    SET TotalRecord = (SELECT
        COUNT(*)
      FROM tmpTable);

    SET StartIndex = (PageSize * (PageNumber - 1));

    SELECT
      *
    FROM tmpTable
    ORDER BY tmpTable.CreatedDate DESC LIMIT StartIndex, PageSize;

  END IF;
END
$$

--
-- Create procedure `Proc_GetEmployees`
--
CREATE DEFINER = 'hieunv'@'%'
PROCEDURE Proc_GetEmployees ()
COMMENT 'Lấy toàn bộ danh sách nhân viên'
BEGIN
  SELECT
    *
  FROM view_employees ve;
END
$$

DELIMITER ;

-- 
-- Dumping data for table unit
--
INSERT INTO unit VALUES
('34bd2cef-5026-567c-3b71-153b37881afe', 'DV02', 'Phòng sản xuất', '1970-01-01 00:00:09', 'Adelaida Bergman', '2011-01-05 14:36:46', 'Alaine Hickey'),
('438598e2-2574-4fc8-2626-978952f080e4', 'DV04', 'Phòng nhân sự', '1970-01-01 00:00:01', 'Edgar Adler', '2010-02-25 08:22:49', 'Monroe Gatewood'),
('43a6bdf5-1b6b-451b-3695-2c566fa88632', 'DV05', 'Phòng đao tạo', '1970-01-01 00:31:40', 'Abram Patten', '2015-12-22 12:56:23', 'Trey Christopher'),
('64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'DV07', 'Phòng marketing', '2008-08-20 20:48:30', 'Scot Acker', '1970-01-01 02:13:43', 'Norris Calderon'),
('674934cc-42cf-20cf-1d4a-aea48a10ed18', 'DV01', 'Phòng công nghệ', '1970-01-01 00:00:07', 'Albert Mclean', '2009-11-26 17:51:54', 'Aileen Pitts');

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'NV-483', 'Đỗ Đình Ánh', '1987-02-14', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '0', '1978-04-25', 'Thanh Hóa', 'Thư kí', '970 Riddle Hill Pkwy, Comcast Building, Albany, New York, 12229', '0944138643', '02488319438', 'Rudd94@gmail.com', '3912169493', 'ShinhanBank', 'Hà Tĩnh', '1999-02-20 22:07:27', 'Jason Blackmon', '1988-11-04 05:04:33', 'Reina Adkins'),
('1152da18-24d8-65b6-0380-e8e2a817c80e', 'NV-170', 'Lê Trường Long', '1966-09-08', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'A8', '1977-01-13', 'Thanh Hóa', 'Dev', '1321 9th Circle, Bismarck, North Dakota, 66160', '0968544909', '02475528146', 'Tandy.Corbitt@gmail.com', '7308666765', 'TechcomBank', 'Hà Bắc', '1984-05-22 17:56:52', 'Marylin Bankston', '1970-01-01 00:05:07', 'Merissa Minter'),
('119af01c-406e-1565-a77d-e8c757976496', 'NV-294', 'Đào Ngọc Thắng', '1951-04-01', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '8SXRAD', '1970-04-01', 'Hà Tĩnh', 'Trưởng phòng', '2977 Town Parkway, 2nd FL, Oklahoma City, OK, 92585', '0998401836', '02484558339', 'Douglas_Mcleod421@gmail.com', '6508814459', 'TechcomBank', 'Hà Tĩnh', '1970-01-01 00:01:31', 'Angel Molina', '1970-01-01 02:16:16', 'Vicki Albertson'),
('11f7089b-33e6-371a-f817-7000f455f3d5', 'NV-118', 'Uông Huỳnh Linh', '1979-02-22', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'EV', '2020-09-02', 'Cần Thơ', 'Bảo vệ', '1752 East Chapel Hill Highway, Austin, Texas, 53257', '0928647881', '02423990345', 'StefanDixon687@sis.hust.edu.vn', '7756120367', 'VietinBnak', 'Hà Bắc', '2013-01-16 16:22:58', 'Corinna Bratton', '1970-01-01 02:09:09', 'Emmett Moulton'),
('124b4a06-7d39-6835-0980-e8e2a817c80e', 'NV-260', 'Đỗ Quốc Đức', '1964-06-01', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '4586F', '1987-01-21', 'Long An', 'Phó phòng', '29 Buttonwood Hwy, Salem, OR, 33546', '0991992332', '02484699631', 'Wiley.Bauman@gmail.com', '5594839744', 'HDBank', 'Hà Nam', '2004-07-27 07:42:20', 'Santo Luttrell', '2004-07-21 22:20:39', 'Ada Ackerman'),
('135e72be-6cdf-5311-a47d-e8c757976496', 'NV-244', 'Trần Minh Sơn', '1952-02-16', 2, '34bd2cef-5026-567c-3b71-153b37881afe', 'D68', '2006-02-19', 'Cao Bằng', 'Shipper', '35 2nd Cir, Macy''s Building, Montgomery, Alabama, 11016', '0940518702', '02462109869', 'RonAbney@gmail.com', '1119795550', 'AgriBank', 'Hà Tiên', '2008-09-05 16:46:29', 'Nickie Oneil', '2019-12-03 22:43:20', 'Marcell Boyle'),
('13fc3540-52b5-3489-1163-eeb1d8ed8cef', 'NV-725', 'Hồ Quốc Phi', '1960-02-15', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '0', '1979-02-15', 'Cần Thơ', 'Phó phòng', '2801 N Mount Blvd, Hartford, CT, 93898', '0923640800', '02462979113', 'qtqf5@sis.hust.edu.vn', '5109278055', 'HDBank', 'Hà Đông', '1970-01-01 00:55:33', 'Justine Allred', '1991-08-22 16:56:11', 'Marcel Casas'),
('141eea25-7b62-62de-8832-6a1673ffca7c', 'NV-916', 'Đào Văn Hiếu', NULL, NULL, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'O', NULL, 'Nghệ An', 'Giám đốc', NULL, NULL, '02416570680', NULL, NULL, NULL, 'Hà Nam', NULL, 'Joel Wilkes', '1998-05-28 20:44:56', 'Ettie Fountain'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'NV-046', 'Đào Trọng Hà', '1952-03-08', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'WCC9', '1971-03-09', 'Hà Nội', 'Shipper', '461 NW Riddle Hill Lane, Concord, NH, 04357', '0999560192', '02446301145', 'Bolt@sis.hust.edu.vn', '5685708272', 'HDBank', 'Hà Tây', '1970-01-01 00:07:13', 'Abraham Acevedo', '1970-01-01 00:00:04', 'Stevie Frizzell'),
('142f0fed-2a8d-534c-1180-e8e2a817c80e', 'NV-973', 'Vũ Đình Trâm', '1951-05-18', 2, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'XU', '1970-05-18', 'Kon Tum', 'Kế toán', '951 Highland Parkway, 2nd Floor, Lincoln, NE, 67950', '0927325935', '02484437687', 'Alcorn@sis.hust.edu.vn', '8003187009', 'TechcomBank', 'Hà Hồi', '1970-01-01 00:02:18', 'Lottie Shackelford', '2004-08-15 00:44:45', 'Cesar Abernathy'),
('14672f47-7abc-2316-a97d-e8c757976496', 'NV-745', 'Hồ Văn Linh', '1951-12-16', 0, '438598e2-2574-4fc8-2626-978952f080e4', '217LY27', '2000-11-09', 'Bắc Giang', 'Phó phòng', '77 SW Waterview Road, 3rd Floor, Carson City, NV, 60011', '0920088736', '02430265465', 'lxsyegok.rppyq@gmail.com', '7666971907', 'BIDV', 'Hà Tây', '2009-11-25 08:17:27', 'Vicki Abney', '1970-01-01 00:00:46', 'Noah Batts'),
('14c0ce35-1687-459c-1acb-66948daf6128', 'NV-608', 'Lê Thị Linh', '1951-04-08', 1, '438598e2-2574-4fc8-2626-978952f080e4', '737987', '1970-04-08', 'Hà Nội', 'Tester', '804 West Bayview Ln, STE 1849, Trenton, NJ, 49680', '0923051102', '02477028681', 'Jasper_Lattimore@sis.hust.edu.vn', '7182885767', 'HDBank', 'Hà Tĩnh', '1970-01-01 00:01:38', 'Dong Alarcon', '1980-07-20 22:16:15', 'Carol Abrams'),
('156a4794-7a9b-5c3e-2bcb-66948daf6128', 'NV-514', 'Phan Minh Thông', '1961-03-27', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '8NQT', '2014-11-17', 'Long An', 'Kế toán', '2855 Mount Hwy, 1st FL, Jackson, MS, 32937', '0986721111', '02440601307', 'AleciaR_Alcala8@sis.hust.edu.vn', '4237606429', 'VPBank', 'Hà Nam', '2018-07-11 23:38:26', 'Arthur Large', '2015-05-09 17:50:46', 'Major Blais'),
('15fb79ad-271b-30eb-8f32-6a1673ffca7c', 'NV-790', 'Bùi Văn Thông', '1976-04-06', 0, '438598e2-2574-4fc8-2626-978952f080e4', '6', '2006-09-27', 'Quảng Bình', 'Lễ tân', '735 Beachwood Ln, Austin, Texas, 29073', '0936920958', '02450474455', 'Canfield@sis.hust.edu.vn', '4730193278', 'MSBBank', 'Hà Tây', '1971-10-01 06:39:31', 'Abel Colburn', '2001-03-03 16:10:53', 'Rhett Abernathy'),
('16d64573-7d44-18a4-2acb-66948daf6128', 'NV-488', 'Nguyễn Ngọc Đức', '1957-02-24', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'D', '1970-05-29', 'Hải Phòng', 'Thư kí', '1771 Cedar Tree Cir, Albany, New York, 69173', '0957218303', '02486509401', 'HoltonJ@sis.hust.edu.vn', '2927723640', 'BIDV', 'Hà Đông', '1980-11-23 02:29:16', 'Alejandra Boyle', '1987-04-16 10:10:54', 'Felix Pereira'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'NV-256', 'Vũ Đình Phi', '1960-01-22', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '7', '1986-11-19', 'Đà Nẵng', 'Tester', '1695 Hidden Deepwood Cir, Superior Bldg, Indianapolis, Indiana, 88231', '0924928302', '02473437357', 'gzzyf7@sis.hust.edu.vn', '4367505134', 'Vietcombank', 'Hà Hồi', '1994-02-26 10:21:29', 'Hong Beaudoin', '1982-02-14 20:20:27', 'Twila Bock'),
('176a5ef0-6a1f-5178-7292-08c864661f9c', 'NV-226', 'Uông Trường Sơn', '1982-01-09', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '6W4', '1973-08-29', 'Đà Nẵng', 'Dev', '3514 Highland Dr, Judge Building, Baton Rouge, LA, 12713', '0969603593', '02493588245', 'MarkusHRankin@gmail.com', '6013758468', 'Vietcombank', 'Hà Tây', '2013-10-05 16:45:20', 'Alexandria Barden', '1975-06-29 23:04:18', 'Adolfo Abbott'),
('1785d6d7-5898-2235-a17d-e8c757976496', 'NV-142', 'Phan Huỳnh Đức', '1997-08-16', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '237', '1973-01-14', 'Hưng Yên', 'Tester', '913 E Riddle Hill Ct, Raleigh, NC, 45680', '0912915923', '02495437663', 'AbbyColley3@gmail.com', '3446509880', 'ShinhanBank', 'Hà Đông', '2008-02-01 02:33:46', 'Niki Adamson', '2003-08-19 15:09:20', 'Elbert Abrams'),
('179d5bc0-2405-67f7-9590-67245e8b283e', 'NV-775', 'Uông Quốc Thơm', '1963-05-14', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '6G', '1982-06-17', 'Hưng Yên', 'Trưởng phòng', '1684 White Sharp Hill Street, Juneau, Alaska, 00157', '0909574685', '02407392174', 'Addie.Angulo@gmail.com', '2606183449', 'VPBank', 'Hà Đông', '1981-02-28 08:46:00', 'Dimple Alba', '2012-03-10 19:57:06', 'Kathleen Burnside'),
('17bf02de-2b93-2829-29cb-66948daf6128', 'NV-843', 'Lê Ngọc Long', '1985-02-24', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'EMJ1T', '1990-07-06', 'Cao Bằng', 'Kế toán', '457 Red Buttonwood Ct, Equitable Bldg, Tallahassee, Florida, 07643', '0906941934', '02433144495', 'Refugio.R_Ackerman4@sis.hust.edu.vn', '2233688690', 'Vietcombank', 'Hà Tây', '1984-05-26 10:16:44', 'Karyn Almanza', '1970-01-01 00:53:22', 'Daron Champagne'),
('19b29f82-468c-1cf8-9232-6a1673ffca7c', 'NV-018', 'Phan Đức Long', '1984-09-14', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '7', '2003-01-25', 'Hà Nội', 'Lễ tân', '3949 Meadowview Ln, Enquirer Building, Santa Fe, NM, 08576', '0962511929', '02430498946', 'LurlineCantrell@sis.hust.edu.vn', NULL, 'Vietcombank', 'Hà Tĩnh', '2010-10-15 21:03:29', 'Adaline Hanson', '1979-04-24 12:15:39', 'Johnny Nolan'),
('1b053175-548d-6448-8bdd-867949feb8b5', 'NV-505', 'Vũ Thị Linh', '1994-06-19', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '4IFN1R4FBR0', '1970-02-02', 'Bắc Kạn"', 'Kế toán', '648 Bayview Drive, Nashville, TN, 98099', '0978287253', '02494718817', 'Anthony@gmail.com', '8060457534', 'MBBank', 'Hà Tây', '1978-03-12 05:09:48', 'Arlen Tilley', '1970-01-01 00:00:03', 'Abby Babcock'),
('1b336f56-7ee3-7ceb-1ccb-66948daf6128', 'NV-255', 'Vũ Văn Nhật', '1951-09-28', 0, '438598e2-2574-4fc8-2626-978952f080e4', 'D', '1970-09-28', 'Long An', 'Tester', '88 Hidden Sharp Hill Way, Oklahoma City, Oklahoma, 88132', '0991453967', '02409566321', 'Saylor@gmail.com', '1888661712', 'HDBank', 'Hà Đông', '1970-01-01 00:04:31', 'Glory Hammond', '1970-01-01 00:00:18', 'Kelley Hiatt'),
('1bf8a43c-47fb-4d6c-1863-eeb1d8ed8cef', 'NV-311', 'Đỗ Thị Na', '1952-03-31', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '0', '1988-05-22', NULL, 'Nhân viên', '134 East Cedar Tree Lane, Hartford, CT, 93847', '0976041067', '02470912907', 'KarylQBunker821@sis.hust.edu.vn', '9896836552', 'ACB', NULL, '1995-12-09 01:10:24', 'Margart Angel', '2011-12-27 23:18:50', NULL),
('1c2187a3-6d94-2ded-21cb-66948daf6128', 'NV-879', 'Lê Minh Thông', '1978-12-22', 1, '438598e2-2574-4fc8-2626-978952f080e4', '7MN', '1978-11-10', 'Nghệ An', 'Phó phòng', '1713 Oak Street, Dover, Delaware, 75251', '0984472823', '02488143937', 'Brant@gmail.com', '9308519012', 'TechcomBank', 'Hà Nội', '2008-05-27 10:41:08', 'Jose Stafford', '2000-12-09 06:26:33', 'Sonny Epps'),
('1ded3dd7-32db-5bc9-9190-67245e8b283e', 'NV-026', 'Vũ Thị Thông', '1965-04-28', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '102', '2013-12-27', 'Hà Tĩnh', 'Bảo vệ', '3949 New Town Blvd, Guardian Building, Phoenix, AZ, 19385', '0918440462', '02447818945', 'FloreneValdez141@gmail.com', '9302538672', 'MBBank', 'Hà Hồi', '1999-07-31 03:49:55', 'Grant Ackerman', '2017-04-19 16:40:25', 'Debby Concepcion'),
('1e5a953f-1c88-5769-addb-e5d54223c257', 'NV-762', 'Phạm Trường Phi', '1952-02-01', 1, '34bd2cef-5026-567c-3b71-153b37881afe', 'J', '1981-02-16', 'Nghệ An', 'Giám đốc', '91 Bayview Dr, Lincoln, NE, 73119', '0932981910', '02464508173', 'AshleyFarris@sis.hust.edu.vn', '6504421916', 'VPBank', 'Hà Đông', '2016-03-23 12:08:39', 'Raphael Ahern', '1996-03-22 12:40:22', 'Alejandro Norwood'),
('1eb07f4e-7018-6d54-6b92-08c864661f9c', 'NV-035', 'Phan Huỳnh Na', NULL, NULL, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '4', NULL, 'Quảng Trị', 'Phó phòng', NULL, NULL, '02419162218', NULL, '3743674682', NULL, 'Hà Bắc', NULL, 'Sebastian Abbott', '1981-08-03 14:53:59', 'Gwenda Vargas'),
('1f22399e-14b4-5c2b-8132-6a1673ffca7c', 'NV-063', 'Đỗ Đức Đạt', '1953-04-10', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '29XU', '2021-05-12', 'Long An', 'Trưởng phòng', '3249 Fox Hill Ct, 1st FL, Saint Paul, Minnesota, 69091', '0965434159', '02444714308', 'Linville632@gmail.com', '0524244616', 'HDBank', 'Hà Tĩnh', '2020-01-08 06:43:23', 'Lianne Aquino', '2021-09-03 16:01:17', 'Jamie Creech'),
('1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'NV-320', 'Nguyễn Quốc Đức', '1951-01-05', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'U', '1970-01-05', NULL, 'Kế toán', '664 Town Way, Oklahoma City, OK, 55081', '0920148823', '02453004299', 'Mckenna@gmail.com', '0660463249', 'HDBank', NULL, '1970-01-01 00:00:05', 'Isreal Dougherty', '1970-01-01 00:56:40', NULL),
('1f8d7e46-1d1e-335f-79dd-867949feb8b5', 'NV-818', 'Phạm Minh Hiếu', '1989-08-12', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'ADS', '2010-12-08', 'Bắc Kạn"', 'Tester', '365 Red Beachwood Ct, Bartlett Building, Montgomery, Alabama, 78518', '0934694344', '02481385116', 'Mccurdy39@sis.hust.edu.vn', '5323252060', 'TechcomBank', 'Hà Hồi', '2018-07-16 16:14:48', 'Abe Addison', '2021-09-03 15:56:25', 'Nathanael Medina'),
('205a3e0a-13fe-3557-8232-6a1673ffca7c', 'NV-892', 'Nguyễn Trọng Hiếu', NULL, NULL, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'Q07I2O', NULL, 'Cao Bằng', 'Kế toán', NULL, NULL, '02471260372', NULL, '4947108452', NULL, 'Hà Tiên', NULL, 'Laurence Deloach', '1981-02-10 13:35:13', 'Johnnie Allard'),
('207bba19-49aa-63f4-88dd-867949feb8b5', 'NV-307', 'Phan Trọng Sơn', '1957-03-05', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '8R7BZ', '1986-09-28', 'Bắc Giang', 'Dev', '71 White Edgewood Lane, Cheyenne, WY, 42467', '0967911378', '02459073133', 'Abdul.Davis@gmail.com', '7632156751', 'HDBank', 'Hà Hồi', '1972-10-30 09:48:41', 'Sherrill Acker', '1970-01-01 00:00:52', 'Kittie Acker'),
('20d0b9f3-3e65-1639-9d7d-e8c757976496', 'NV-048', 'Lê Trường Ánh', '1953-03-01', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '56W00', '1972-03-01', 'Bắc Kạn"', 'Kế toán', '2449 Fox Hill Highway, Atlanta, Georgia, 35095', '0930956691', '02460866980', 'ymasddoh_ywma@gmail.com', '1354219150', 'VietinBnak', 'Hà Tĩnh', '1970-01-01 00:13:11', 'Darell Mireles', '2017-05-27 13:05:01', 'Abe Christie'),
('2152ea1c-3cd9-7d2b-8d32-6a1673ffca7c', 'NV-404', 'Phan Ngọc Hà', '1951-01-18', 0, '34bd2cef-5026-567c-3b71-153b37881afe', NULL, '1974-08-06', 'Hà Nội', NULL, '1588 Old Oak Loop, Montgomery, AL, 52571', '0919044815', NULL, 'loegs28@gmail.com', '8572415733', 'HDBank', 'Hà Tây', '1974-06-28 23:44:49', NULL, NULL, 'Laverne Aiello'),
('22032557-51a3-4005-1263-eeb1d8ed8cef', 'NV-987', 'Phan Trường Thơm', '1951-02-07', 2, '674934cc-42cf-20cf-1d4a-aea48a10ed18', NULL, '1970-02-07', 'Hưng Yên', NULL, '2576 Mountain Ave, Hartford, Connecticut, 17281', '0963053648', NULL, 'AyeshaWicks@gmail.com', '0780002640', 'VietinBnak', 'Hà Nội', '1970-01-01 00:00:38', NULL, NULL, 'Carmelita Abel'),
('22f831e3-5d4e-3508-1480-e8e2a817c80e', 'NV-670', 'Bùi Đình Giang', '1973-06-24', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'AQ1', '1992-06-24', 'Hưng Yên', 'Shipper', '271 NE Ski Hill Ln, Madison, WI, 48138', '0928280119', '02423701786', 'AleshaTrotter3@gmail.com', '2286455037', 'Vietcombank', 'Hà Đông', '1970-01-01 02:16:51', 'Calista Busch', '1970-01-01 00:06:32', 'Archie Sayre'),
('24629593-3d34-32fd-997d-e8c757976496', 'NV-289', 'Nguyễn Trọng Hiếu', '1951-03-29', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '016J', '1970-03-29', 'Quảng Bình', 'Shipper', '37 Market Street, APT 666, Cheyenne, Wyoming, 21327', '0900236884', '02407310747', 'Bock@gmail.com', '1158392309', 'HDBank', 'Hà Nội', '1970-01-01 00:01:28', 'Juan Whitten', '2014-10-04 03:03:55', 'Britt Malley'),
('247986de-4165-651a-9490-67245e8b283e', 'NV-171', 'Đỗ Trọng Thắng', '1981-03-28', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'K90', '2020-12-23', 'Kon Tum', 'Lễ tân', '3747 Farmview Blvd, Bartlett Building, Olympia, WA, 43866', '0925906239', '02460488787', 'Blaylock3@gmail.com', '5744777836', 'MBBank', 'Hà Hồi', '1982-11-21 04:22:32', 'Sanford Dyson', '2010-10-23 22:16:07', 'Raphael Beckman'),
('2508b8b3-3851-6ae9-86dd-867949feb8b5', 'NV-140', 'Lê Văn Long', '1969-06-11', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '6', '1971-06-15', NULL, 'Thư kí', '210 NW Ironwood Ln, Columbia, South Carolina, 26445', '0909585557', '02456048850', 'khrjf454@gmail.com', '2054082467', 'Vietcombank', NULL, '1993-01-04 03:33:37', 'Edmund Schwab', '1970-01-01 00:06:29', NULL),
('257ea484-501b-1644-7cdd-867949feb8b5', 'NV-788', 'Phan Minh Na', '1989-07-13', 0, '34bd2cef-5026-567c-3b71-153b37881afe', 'I69UV592K5OF', '1974-12-19', 'Quảng Bình', 'Kế toán', '2982 Monument St, Little Rock, Arkansas, 15153', '0990301247', '02482687457', 'Little@gmail.com', '0135882468', 'Vietcombank', 'Hà Đông', '1987-08-02 03:05:30', 'Demarcus Aponte', '2010-04-16 12:32:04', 'Isela Crittenden'),
('258eee01-5e19-7ac4-2ccb-66948daf6128', 'NV-883', 'Trần Long Giang', '1951-02-06', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'F702T', '1970-02-06', 'Nghệ An', 'Phó phòng', '3524 NW Beachwood Court, Baton Rouge, LA, 71588', '0964502426', '02498120884', 'DanaDougherty967@gmail.com', NULL, 'ACB', 'Hà Nam', '1970-01-01 00:00:37', 'Barb Enos', '1975-12-08 15:22:34', 'Geraldine Hoover'),
('25efaa0a-2220-4655-20cb-66948daf6128', 'NV-143', 'Đào Trường Long', '1990-07-02', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'A8', '1974-11-07', 'Bắc Kạn"', 'Phó phòng', '1981 Oak Drive, Oklahoma City, OK, 79763', '0913791597', '02476906395', 'Vanmeter@gmail.com', '8659467376', 'AgriBank', 'Hà Tĩnh', '2019-04-15 23:43:04', 'Luke Emanuel', '1972-03-11 11:53:06', 'Lewis Kurtz'),
('276e9765-4c6a-4239-0b80-e8e2a817c80e', 'NV-289', 'Nguyễn Trường Hiếu', '1982-10-12', 2, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'XU', '1992-12-02', 'Kon Tum', 'Phó phòng', '2238 Fox Hill Blvd, Dover, Delaware, 08714', '0952212620', '02424779458', 'Flor.UAbbott@gmail.com', '0579757294', 'Vietcombank', 'Hà Hồi', '2004-10-10 04:01:42', 'Alane Dewitt', '1983-11-15 05:17:13', 'Ada Acevedo'),
('27a76ea6-6309-6d6a-0218-7000f455f3d5', 'NV-703', 'Hồ Ngọc Hiếu', '1973-11-05', 0, '438598e2-2574-4fc8-2626-978952f080e4', NULL, '1984-02-22', 'Thanh Hóa', NULL, '3788 Old Oak Hwy, Nipper Building, Albany, New York, 50662', '0971719388', NULL, 'Barrios@gmail.com', '4287053392', 'MBBank', 'Hà Hồi', '1993-04-30 10:08:20', NULL, NULL, 'Cristin Batiste'),
('27e293c1-483b-5599-a090-67245e8b283e', 'NV-271', 'Đỗ Huỳnh Thông', '1951-01-26', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'M59951', '1970-01-26', 'Cần Thơ', 'Phó phòng', '391 Beachwood Way, Springfield, IL, 87126', '0972777875', '02413563191', 'Augustine_Riggs73@gmail.com', '7023840733', 'AgriBank', 'Hà Bắc', '1970-01-01 00:00:26', 'John Beyer', '1970-01-01 00:00:38', 'Casey Pendergrass'),
('284ccb05-337b-7e6f-9090-67245e8b283e', 'NV-782', 'Đỗ Quốc Thơm', '1971-10-13', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '04', '1975-11-16', 'Cần Thơ', 'Trưởng phòng', '1765 Ironwood Hwy, Kearns Bldg, Juneau, AK, 44263', '0961089761', '02476348115', 'Cervantes4@sis.hust.edu.vn', '6454081385', 'ACB', 'Hà Nam', '2004-02-03 16:13:01', 'Deandre Ortiz', '1970-01-01 00:00:25', 'Loise Mayers'),
('28e5fd74-7c2e-6105-26cb-66948daf6128', 'NV-003', 'Đỗ Văn Trâm', '1966-04-14', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '2', '1985-04-14', 'Hà Nội', 'Giám đốc', '2603 Cedar Tree Loop, Bismarck, North Dakota, 80526', '0949248492', '02417149876', 'BroderickDanielson97@sis.hust.edu.vn', '9010454931', 'MSBBank', 'Hà Nội', '1970-01-01 01:33:03', 'Erna Matheson', '1970-01-01 00:00:55', 'Gale Eller'),
('2a2516e8-7ca5-62b3-9132-6a1673ffca7c', 'NV-035', 'Đỗ Ngọc Giang', '1951-06-13', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'L10QY7UF', '1970-06-13', 'Hưng Yên', 'Tester', '3182 Town Loop, Nashville, TN, 11897', '0941324499', '02411549769', 'Eddy@sis.hust.edu.vn', NULL, 'VietinBnak', 'Hà Tiên', '1970-01-01 00:02:44', 'Albert Pape', '1970-01-01 00:00:03', 'Ryan Roberge'),
('2b850d3d-6722-3f01-1bcb-66948daf6128', 'NV-550', 'Uông Văn Giang', '1968-03-20', 2, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'Z569M8843208', '2008-06-12', 'Long An', 'Dev', '718 NW Hunting Hill Blvd, Albany, New York, 70768', '0964095063', '02456225776', 'LenardV.Keene664@sis.hust.edu.vn', '5352603470', 'ACB', 'Hà Tây', '2011-12-10 11:26:19', 'Abraham Berryman', '1970-01-01 00:00:13', 'Abdul Bergstrom'),
('2bbbd485-6df2-536a-7e32-6a1673ffca7c', 'NV-315', 'Uông Huỳnh Long', '1951-03-05', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'FL8', '1970-03-05', 'Hà Nội', 'Tester', '62 Ashwood Pkwy, 3rd Floor, Madison, Wisconsin, 04370', '0917493116', '02457429436', 'EmileJohnston@gmail.com', '3278647383', 'ACB', 'Hà Đông', '1970-01-01 00:01:04', 'Peggy Charlton', '1976-10-20 23:05:48', 'Raul Palma'),
('2bf413d3-7a2c-217a-78dd-867949feb8b5', 'NV-848', 'Vũ Thị Linh', '1977-06-02', 0, '438598e2-2574-4fc8-2626-978952f080e4', '7192', '1986-12-23', 'Thanh Hóa', 'Phó phòng', '729 Meadowview Drive, Hartford, Connecticut, 90181', '0950433775', '02491082248', 'Rushing342@sis.hust.edu.vn', '6483149959', 'BIDV', 'Hà Nam', '1970-09-06 03:17:31', 'Adah Acker', '2003-02-04 02:42:07', 'Magdalena Ogle'),
('2c4d181d-6dbb-4b03-87dd-867949feb8b5', 'NV-430', 'Lê Minh Na', '1969-11-24', 0, '34bd2cef-5026-567c-3b71-153b37881afe', '6HM', '1996-10-17', 'Bắc Kạn"', 'Nhân viên', '80 Riddle Hill Ct, Judge Building, Atlanta, Georgia, 63305', '0955950506', '02490823346', 'AndresThacker95@gmail.com', '1414342019', 'ACB', 'Hà Bắc', '2002-10-11 09:03:21', 'Tod Thornton', '2005-07-30 12:56:38', 'Cathern Pridgen'),
('2c7af5cb-448b-1c53-a57d-e8c757976496', 'NV-840', 'Bùi Huỳnh Thắng', '1952-08-15', 2, '438598e2-2574-4fc8-2626-978952f080e4', NULL, '1971-08-16', 'Bắc Kạn"', NULL, '1144 Highland Ln, Helena, Montana, 93064', '0951454764', NULL, 'BurtonM@gmail.com', '3302325187', 'Vietcombank', 'Hà Nam', '1970-01-01 00:09:53', NULL, NULL, 'Bryan Abney'),
('2d19b0e8-2a06-52dc-a190-67245e8b283e', 'NV-266', 'Đỗ Minh Thơm', '1975-08-06', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'H6', '2017-07-12', 'Quảng Trị', 'Bảo vệ', '672 Mount Court, Sacramento, CA, 47224', '0973508362', '02444928152', 'Lynda.Rizzo@gmail.com', '8703627154', 'AgriBank', 'Hà Hồi', '2014-04-17 07:22:34', 'Ada Ridenour', '1970-01-01 02:21:45', 'Reuben Mcallister'),
('2d558039-6f60-6d55-fd17-7000f455f3d5', 'NV-757', 'Hồ Trường Trâm', '1957-03-13', 0, '438598e2-2574-4fc8-2626-978952f080e4', 'XBTJ167S93D25Z', '1976-03-13', 'Bắc Giang', 'Tester', '490 West Parkwood St, Montgomery, Alabama, 90655', '0903116206', '02452796408', 'Holden@sis.hust.edu.vn', '1810775825', 'AgriBank', 'Hà Tây', '1970-01-01 00:37:44', 'Allyson Cole', '1974-08-13 23:42:57', 'Nicolas Dyer'),
('2dcedb9c-6c32-7d27-977d-e8c757976496', 'NV-734', 'Phan Trọng Đức', '1954-11-21', 1, '438598e2-2574-4fc8-2626-978952f080e4', '81J', '1999-01-08', 'Nghệ An', 'Lễ tân', '3235 NW Farmview Loop, Boston, Massachusetts, 65476', '0969994086', '02402147090', 'Crist@sis.hust.edu.vn', '8979666073', 'Vietcombank', 'Hà Tây', '2004-04-19 22:38:32', 'Adelaida Laporte', '1985-09-06 20:32:47', 'Kayleen Hogg'),
('2de001fe-529b-33ad-0280-e8e2a817c80e', 'NV-121', 'Uông Đình Thơm', '1953-03-20', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '44', '1999-04-12', 'Hải Phòng', 'Tester', '283 Sharp Hill Parkway, STE 8682, Dover, Delaware, 25934', '0978017955', '02453652795', 'OpheliaSerna872@sis.hust.edu.vn', '0312942590', 'ACB', 'Hà Nam', '2014-03-31 09:36:01', 'Molly Bobo', '2005-06-06 11:18:26', 'Camie Burch'),
('2fb0b105-7808-503a-76dd-867949feb8b5', 'NV-945', 'Lê Long Hà', NULL, NULL, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '5186E4', NULL, 'Cao Bằng', 'Bảo vệ', NULL, NULL, '02414816653', NULL, '0430967329', NULL, 'Hà Tiên', NULL, 'Arthur Beane', '2013-07-21 00:06:53', 'Kecia Adcock'),
('2fc95768-5570-6429-28cb-66948daf6128', 'NV-201', 'Uông Quốc Na', NULL, NULL, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'CG10113', NULL, 'Hà Nội', 'Shipper', NULL, NULL, '02476425779', NULL, '0749261056', NULL, 'Hà Hồi', NULL, 'Nannie Farr', '1970-01-01 00:04:16', 'Tori Cloud'),
('2ff059da-69a9-17a4-fc17-7000f455f3d5', 'NV-558', 'Uông Huỳnh Đức', '1965-08-26', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '4', '2017-10-10', NULL, 'Bảo vệ', '1768 South Market Ct, Phoenix, AZ, 26004', '0909769527', '02498277534', 'Barbour@gmail.com', '9483141131', 'AgriBank', NULL, '1978-01-20 23:09:07', 'Adah Bundy', '1970-01-01 00:00:12', NULL),
('30c8ee28-58a3-22f2-5e92-08c864661f9c', 'NV-559', 'Uông Quốc Linh', NULL, NULL, '438598e2-2574-4fc8-2626-978952f080e4', '287N8G8H', NULL, 'Bắc Kạn"', 'Lễ tân', NULL, NULL, '02442428078', NULL, '6025564077', NULL, 'Hà Nội', NULL, 'Zula Apodaca', '1970-01-01 00:00:04', 'Luis Cruse'),
('30f30be1-5707-6c05-1a63-eeb1d8ed8cef', 'NV-621', 'Đỗ Trường Sơn', '1955-10-04', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '93C8EGJY0KS602', '2020-06-22', NULL, 'Dev', '3292 Fox Hill Street, Phoenix, Arizona, 12907', '0999521607', '02484082331', 'Addie.Sanderson3@sis.hust.edu.vn', '6009648483', 'ACB', NULL, '1986-03-31 12:43:13', 'Adam Sanford', '1973-02-18 12:01:28', NULL),
('31584a21-584a-7428-0d80-e8e2a817c80e', 'NV-695', 'Nguyễn Văn Linh', '1967-07-29', 0, '34bd2cef-5026-567c-3b71-153b37881afe', '5617', '1986-07-29', 'Kon Tum', 'Shipper', '1136 White Riverside Pkwy, Judge Bldg, Denver, CO, 09517', '0955711664', '02431742218', 'EmmittAdams@gmail.com', '1142213912', 'VietinBnak', 'Hà Tiên', '1970-01-01 01:40:54', 'Millard Crowley', '2016-01-17 14:56:57', 'Adalberto Guerrero'),
('336f81b7-417d-7e3a-1363-eeb1d8ed8cef', 'NV-489', 'Trần Đình Phi', '1951-01-10', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'J8X', '1970-01-10', 'Bắc Giang', 'Thư kí', '791 3rd Ln, Olympia, WA, 62499', '0996962133', '02497883125', 'Bair643@sis.hust.edu.vn', '1325540120', 'MBBank', 'Hà Tĩnh', '1970-01-01 00:00:10', 'Torrie Aguilar', '1970-01-01 00:00:44', 'Adela Payne'),
('33851c36-6445-4680-23cb-66948daf6128', 'NV-436', 'Đào Bảo Na', '1974-02-17', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '8Q', '1993-02-17', 'Bắc Giang', 'Giám đốc', '2220 2nd Ln, Victor Executive Bldg, Columbus, Ohio, 39384', '0972504456', '02497246920', 'HawksX@gmail.com', '7919877994', 'BIDV', 'Hà Tĩnh', '1970-01-01 02:20:49', 'Benito Monahan', '1979-03-23 19:34:36', 'Crissy Adler'),
('34cde64f-62e4-186c-77dd-867949feb8b5', 'NV-452', 'Bùi Quốc Hiếu', '1988-12-11', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '1', '2006-03-27', 'Quảng Trị', 'Trưởng phòng', '546 NW Waterview Blvd, Duke Energy Building, Charleston, WV, 15053', '0939871780', '02448098974', 'OlgaFerry@gmail.com', NULL, 'MBBank', 'Hà Tây', '1977-10-06 07:09:55', 'Scott Rich', '1970-01-01 00:16:31', 'Adah Adair'),
('3590dd80-43d2-1325-8732-6a1673ffca7c', 'NV-247', 'Hồ Ngọc Thắng', '1977-02-15', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'J604NY', '2004-03-31', 'Kon Tum', 'Lễ tân', '40 Hidden Mountain Court, Tallahassee, FL, 94804', '0950194157', '02444054028', 'Aiken329@gmail.com', '1302217873', 'HDBank', 'Hà Tĩnh', '2019-12-03 16:59:05', 'Arlinda Acker', '1970-01-01 00:00:07', 'Aileen Ricks'),
('3599ef50-13ed-5404-0e63-eeb1d8ed8cef', 'NV-516', 'Phan Thị Thông', '1966-10-18', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'J63S', '2018-02-27', 'Long An', 'Phó phòng', '1912 E Deepwood Ave, Austin, Texas, 55348', '0990706288', '02413875191', 'nieumt0@gmail.com', '2852360928', 'HDBank', 'Hà Hồi', '1988-04-21 02:03:00', 'Alease Montoya', '1977-05-28 09:00:02', 'Maurice Mireles'),
('3721d21d-5c1d-1e10-1563-eeb1d8ed8cef', 'NV-168', 'Lê Minh Linh', '1964-07-10', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '2L', '2021-08-30', 'Thanh Hóa', 'Tester', '2228 South Beachwood Parkway, Comcast Building, Augusta, Maine, 49513', '0914537559', '02427726318', 'Chamberlain@gmail.com', '5481819131', 'MBBank', 'Hà Nội', '2007-12-29 21:14:00', 'Woodrow Means', '1981-10-09 17:52:22', 'Conrad Bell'),
('37cf0ec7-4909-5dc9-a37d-e8c757976496', 'NV-769', 'Uông Huỳnh Thắng', '1998-05-06', 0, '438598e2-2574-4fc8-2626-978952f080e4', 'A8QFR84AX9VZ977', '1996-10-03', 'Cần Thơ', 'Thư kí', '3079 Lake Circle, Judge Bldg, Raleigh, NC, 84991', '0925579047', '02445987266', 'Zaragoza@gmail.com', '9794126666', 'VietinBnak', 'Hà Tây', '1981-08-02 15:48:15', 'Lourdes Klein', '1976-05-27 21:21:47', 'Nevada Rios'),
('380799e8-2bfa-4f0f-8e32-6a1673ffca7c', 'NV-280', 'Nguyễn Ngọc Hiếu', NULL, NULL, '438598e2-2574-4fc8-2626-978952f080e4', NULL, NULL, 'Kon Tum', NULL, NULL, NULL, NULL, NULL, '8950927050', NULL, 'Hà Đông', NULL, NULL, NULL, 'Antoinette Adler'),
('3856e8f7-535c-632a-83dd-867949feb8b5', 'NV-187', 'Bùi Đình Thơm', '1952-06-06', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '8L', '1971-06-07', 'Hà Tĩnh', 'Lễ tân', '3929 Woodrow Ct, Cheyenne, WY, 35072', '0945704177', '02476145135', 'pvgx04@sis.hust.edu.vn', '1024344166', 'Vietcombank', 'Hà Tiên', '1970-01-01 00:08:43', 'Numbers Darby', '1970-01-01 00:07:04', 'Adolph Thrash'),
('38b1d642-47b7-7c97-6692-08c864661f9c', 'NV-415', 'Phạm Trường Nhật', '1961-08-11', 1, '34bd2cef-5026-567c-3b71-153b37881afe', NULL, '2001-01-03', 'Hà Nội', NULL, '161 Hidden Woodcock Lane, Indianapolis, Indiana, 50144', '0941727194', NULL, 'Titus_Abraham757@gmail.com', '9656065879', 'Vietcombank', 'Hà Nam', '2005-07-29 13:31:03', NULL, NULL, 'Deena Seifert'),
('392fb6ca-399e-2320-7192-08c864661f9c', 'NV-118', 'Vũ Thị Thắng', NULL, NULL, '438598e2-2574-4fc8-2626-978952f080e4', '917', NULL, 'Quảng Trị', 'Nhân viên', NULL, NULL, '02436823311', NULL, '1944761135', NULL, 'Hà Bắc', NULL, 'Hazel Withers', '1978-03-26 13:46:18', 'Jerome Barber'),
('3965bd1a-2544-467d-80dd-867949feb8b5', 'NV-706', 'Trần Văn Thắng', '1993-12-31', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '4M46', '2009-03-13', 'Bắc Giang', 'Dev', '87 Hazelwood Cir, 6th Floor, Austin, Texas, 54177', '0916691151', '02491715964', 'vfdpiabb_mjai@gmail.com', '1490505666', 'VietinBnak', 'Hà Tiên', '1992-02-20 11:18:58', 'Dalia Loy', '1970-01-01 00:01:09', 'Shawnda Cameron'),
('3ab17eb8-4928-4275-8332-6a1673ffca7c', 'NV-353', 'Bùi Đức Ánh', '1953-02-14', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'JQ6TV8QBV8', '1978-08-26', 'Thanh Hóa', 'Kế toán', '3156 Red Lake Court, Providence, Rhode Island, 27203', '0953571462', '02477375602', 'zigg5@sis.hust.edu.vn', '7368504077', 'BIDV', 'Hà Tĩnh', '2008-11-28 11:30:12', 'Marianne Terry', '2013-01-13 18:06:15', 'Pearlene Starnes'),
('3abc4ce5-462f-5db9-9e7d-e8c757976496', 'NV-622', 'Phan Thị Trâm', '1951-02-05', 0, '438598e2-2574-4fc8-2626-978952f080e4', NULL, '1970-02-05', 'Kon Tum', NULL, '2539 North Monument Rd, Standard Building, Indianapolis, Indiana, 41421', '0960650779', NULL, 'JuarezU@gmail.com', '9426108946', 'MSBBank', 'Hà Bắc', '1970-01-01 00:00:36', NULL, NULL, 'Herschel Allison'),
('3b4d46a3-7a40-30a2-fe17-7000f455f3d5', 'NV-529', 'Phan Long Giang', '1972-05-07', 0, '34bd2cef-5026-567c-3b71-153b37881afe', 'E4', '1991-05-08', 'Thanh Hóa', 'Giám đốc', '2616 N Mount Street, Jefferson City, Missouri, 81997', '0929347400', '02474945542', 'Sells576@gmail.com', '4666122742', 'MSBBank', 'Hà Tĩnh', '1970-01-01 02:09:58', 'Jeffry Earls', '2014-06-01 19:36:34', 'Letha Allison'),
('3b58cf74-16ac-69f6-aa7d-e8c757976496', 'NV-382', 'Bùi Long Giang', '1951-03-30', 0, '34bd2cef-5026-567c-3b71-153b37881afe', '1X8NJ', '1970-03-30', 'Đà Nẵng', 'Phó phòng', '1173 Lake Dr, Juneau, Alaska, 49763', '0943246093', '02428037026', 'OpheliaShelby898@gmail.com', '8848195016', 'ShinhanBank', 'Hà Tĩnh', '1970-01-01 00:01:29', 'Raymundo Abernathy', '1985-04-04 08:22:37', 'Tari Dickerson'),
('3c19bf05-3077-4b76-27cb-66948daf6128', 'NV-221', 'Lê Huỳnh Sơn', '1970-06-29', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'Z2', '2012-11-02', 'Quảng Bình', 'Kế toán', '953 E Hope Road, 3rd Floor, Juneau, AK, 51333', '0914234689', '02452846691', 'BarbAbernathy@gmail.com', NULL, 'VPBank', 'Hà Tây', '1973-05-06 06:38:57', 'Theodora Abernathy', '1994-08-16 01:08:09', 'Coleman Chase'),
('3ce59559-28e3-40e4-1463-eeb1d8ed8cef', 'NV-519', 'Bùi Bảo Linh', '1964-07-06', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '8H445V6O85CIX', '1997-01-22', 'Cần Thơ', 'Lễ tân', '2785 Rushwood Highway, Augusta, Maine, 68431', '0925120016', '02479705816', 'xhmuhz2@sis.hust.edu.vn', NULL, 'TechcomBank', 'Hà Đông', '1986-11-22 20:14:40', 'Danilo Brandenburg', '1970-03-08 13:29:16', 'Lien Alicea'),
('3d780ac8-3fb5-5c89-8932-6a1673ffca7c', 'NV-732', 'Phạm Ngọc Nhật', NULL, NULL, '34bd2cef-5026-567c-3b71-153b37881afe', NULL, NULL, 'Đà Nẵng', NULL, NULL, NULL, NULL, NULL, '8478100773', NULL, 'Hà Tây', NULL, NULL, NULL, 'Catherin Gaither'),
('3ef08d53-5bf3-1e97-9790-67245e8b283e', 'NV-921', 'Trần Trường Nhật', '1967-12-24', 0, '34bd2cef-5026-567c-3b71-153b37881afe', NULL, '2010-04-22', 'Hải Phòng', NULL, '39 Parkwood Blvd, Calyon Building, Phoenix, AZ, 00283', '0925738749', NULL, 'Keeler@gmail.com', '8755703180', 'ShinhanBank', 'Hà Hồi', '2017-12-25 16:53:40', NULL, '2021-09-03 16:03:16', 'Rick Trevino'),
('3f66f2d6-688b-4161-5f92-08c864661f9c', 'NV-263', 'Nguyễn Minh Phi', '2000-01-08', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'K9B', '2010-03-05', 'Cao Bằng', 'Lễ tân', '92 3rd Ct, Montpelier, Vermont, 60820', '0950929850', '02455678137', 'ColletteFennell@sis.hust.edu.vn', '6574909328', 'Vietcombank', 'Hà Đông', '1971-02-27 16:16:31', 'Rubi Hobbs', '1977-04-17 02:22:03', 'Henry Crump'),
('3f851737-2976-4bc0-22cb-66948daf6128', 'NV-513', 'Vũ Đức Linh', '1963-06-12', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '8', '1972-09-01', 'Hà Tĩnh', 'Shipper', '781 Old Beachwood Dr, Penobscot Bldg, Pierre, South Dakota, 64728', '0903607218', '02469614366', 'Abney54@sis.hust.edu.vn', '3180060602', 'TechcomBank', 'Hà Nam', '1996-06-16 21:27:17', 'Johnny Brubaker', '1976-02-07 10:49:21', 'Morgan Burt'),
('3fcda397-772d-53a4-25cb-66948daf6128', 'NV-816', 'Hồ Đình Thông', '1951-01-01', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '9R2OQ', '1970-01-01', 'Cao Bằng', 'Phó phòng', '3697 East Pine Tree Drive, Helena, MT, 94331', '0977704256', '02481030627', 'AbelMartino@sis.hust.edu.vn', '3229236183', 'VPBank', 'Hà Bắc', '1970-01-01 00:00:01', 'Albertine Carmona', '1998-11-27 14:42:17', 'Christoper Suarez'),
('40036f5e-657f-2c3d-9f7d-e8c757976496', 'NV-238', 'Phan Văn Giang', NULL, NULL, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'L3M29', NULL, 'Quảng Bình', 'Giám đốc', NULL, NULL, '02470967588', NULL, NULL, NULL, 'Hà Đông', NULL, 'Martina Darden', '1970-01-01 00:00:39', 'Seth Martin'),
('404fe340-1fd3-414b-aadb-e5d54223c257', 'NV-764', 'Đỗ Ngọc Nhật', '1951-03-24', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '7H', '1970-03-24', 'Thanh Hóa', 'Phó phòng', '44 White Glenwood Court, Appartment 9, Salt Lake City, Utah, 30714', '0986902047', '02462885565', 'Ali@gmail.com', '8534222326', 'ACB', 'Hà Hồi', '1970-01-01 00:01:23', 'Alene Ambrose', '1970-01-01 00:57:34', 'Kent Staton'),
('4103f42d-1ebd-52dd-0f80-e8e2a817c80e', 'NV-214', 'Uông Đình Linh', '1977-02-01', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '0UGP47Y0', '1987-03-04', 'Thanh Hóa', 'Nhân viên', '2800 Sharp Hill Rd, Bartlett Building, Tallahassee, Florida, 08433', '0980144186', '02417653282', 'Hung_Alonzo@gmail.com', '7935387529', 'VPBank', 'Hà Nội', '1979-02-25 08:35:38', 'Dessie Zielinski', '2007-05-05 21:22:09', 'Georgann Bergeron'),
('4188bc78-6e7e-2c0a-7fdd-867949feb8b5', 'NV-686', 'Phạm Thị Hiếu', '1953-08-30', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'I', '1972-08-30', 'Hải Phòng', 'Phó phòng', '1362 New Sharp Hill Way, Duke Energy Bldg, Annapolis, Maryland, 31040', '0968892697', '02429483219', 'Rayford2@sis.hust.edu.vn', '2384878038', 'MSBBank', 'Hà Tây', '1970-01-01 00:16:13', 'Jonas Runyon', '2007-05-25 18:42:54', 'Darwin Aguirre'),
('4213347c-7d41-76e6-9d90-67245e8b283e', 'NV-864', 'Đào Văn Long', '1980-11-21', 2, '438598e2-2574-4fc8-2626-978952f080e4', 'W7P3MJF68', '1988-05-27', 'Kon Tum', 'Lễ tân', '216 North Ironwood Parkway, 1st FL, Jefferson City, Missouri, 33048', '0912229481', '02404580600', 'Maragaret_Bolton@gmail.com', '7405052233', 'VPBank', 'Hà Tiên', '1999-05-12 11:51:30', 'Abram Coleman', '1970-01-01 00:00:03', 'Rosann Dockery'),
('4296b118-76aa-3241-7edd-867949feb8b5', 'NV-875', 'Phan Trường Hà', '1951-01-02', 2, '438598e2-2574-4fc8-2626-978952f080e4', '18', '1970-01-02', 'Kon Tum', 'Lễ tân', '985 Hunting Hill Highway, Indianapolis, IN, 20437', '0975961223', '02418547545', 'Erlinda_E.Dolan@sis.hust.edu.vn', '5543911974', 'BIDV', 'Hà Đông', '1970-01-01 00:00:02', 'Everett Howard', '1995-08-21 09:22:52', 'Maynard Mullins'),
('438fec4c-2dad-30d7-a07d-e8c757976496', 'NV-501', 'Lê Long Nam', '1979-04-29', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', NULL, '1971-01-24', NULL, NULL, '43 Ski Hill Loop, Victor Executive Building, Boise, Idaho, 58799', '0985100834', NULL, 'Catalina.Rector@sis.hust.edu.vn', '6006912693', 'MBBank', NULL, '2012-12-20 13:30:36', NULL, '2021-09-01 17:48:39', NULL),
('439cdac8-4380-1e2d-0f63-eeb1d8ed8cef', 'NV-650', 'Lê Đình Phi', NULL, NULL, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '7F1B9Z26Z41K1', NULL, 'Bắc Kạn"', 'Dev', NULL, NULL, '02403059784', NULL, '3576800249', NULL, 'Hà Hồi', NULL, 'Bianca Emery', '1970-01-01 00:07:20', 'Enoch Dortch'),
('4448a185-202a-56da-8632-6a1673ffca7c', 'NV-333', 'Phan Quốc Thông', '1966-06-06', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '6U', '2011-01-08', 'Cần Thơ', 'Tester', '349 West Ski Hill Hwy, Comcast Bldg, Albany, NY, 27993', '0998845003', '02477123802', 'Blakely@gmail.com', '0164375671', 'AgriBank', 'Hà Tiên', '2014-09-23 15:20:50', 'Elmer Serrano', '2021-09-03 16:03:16', 'Rudolph Staley'),
('453b5c4b-7d14-117d-0418-7000f455f3d5', 'NV-901', 'Bùi Đức Sơn', '1953-04-22', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'Y1988XV2YIW766A51G', '1972-04-22', 'Hà Tĩnh', 'Nhân viên', '2980 Riverside Ct, Dover, DE, 11068', '0912136225', '02448752739', 'Odell_RDooley@sis.hust.edu.vn', NULL, 'AgriBank', 'Hà Tây', '1970-01-01 00:14:03', 'Adelaida Ames', '2006-02-11 04:59:05', 'Crystle Bergeron'),
('45536100-7fba-5a99-24cb-66948daf6128', 'NV-995', 'Lê Bảo Đức', '1980-10-06', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'S799FI', '1989-01-13', 'Cần Thơ', 'Kế toán', '1314 Rushwood Dr, MidAmerican Building, Trenton, NJ, 68234', '0950807652', '02440681353', 'HoweQ@sis.hust.edu.vn', '9297462999', 'AgriBank', 'Hà Tiên', '1975-12-09 23:07:16', 'Adaline Gilley', '2005-12-27 06:11:04', 'Alfredia Bryan'),
('4577565a-7e3e-493a-74dd-867949feb8b5', 'NV-167', 'Lê Ngọc Giang', '1990-04-29', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'J6O', '1998-12-05', 'Thanh Hóa', 'Thư kí', '2844 North Woodfort St, Raleigh, NC, 26635', '0960842012', '02432138656', 'Weems@gmail.com', '4332535066', 'ShinhanBank', 'Hà Nam', '1971-12-30 22:25:59', 'Tiny Card', '1976-01-06 18:06:16', 'Lavonia Whiteside'),
('45a563b4-28b0-60dc-bbdb-e5d54223c257', 'NV-410', 'Bùi Trường Hiếu', '1998-08-19', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '536', '1973-03-17', 'Kon Tum', 'Giám đốc', '2227 Hunting Hill Highway, Columbus, OH, 50649', '0924298974', '02430553242', 'Chadwick.G_Gerber@gmail.com', '8319109281', 'ACB', 'Hà Tĩnh', '2014-04-30 01:33:22', 'Bert Woodson', '2002-06-08 16:14:13', 'Tristan Amaya'),
('46377235-7295-534b-a390-67245e8b283e', 'NV-543', 'Lê Thị Phi', '1992-09-15', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '563', '2004-07-29', 'Nghệ An', 'Nhân viên', '987 Cedar Tree Way, Raleigh, North Carolina, 29528', '0985851607', '02422615545', 'Avery_Abrams@sis.hust.edu.vn', NULL, 'Vietcombank', 'Hà Tĩnh', '2017-08-11 05:38:37', 'Humberto Styles', '2011-12-28 07:10:52', 'Gertude Weir'),
('469b3ece-744a-45d5-957d-e8c757976496', 'NV-652', 'Uông Đức Thông', '1970-09-20', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '4WA7', '1982-03-02', NULL, 'Giám đốc', '11 Red Lake Hwy, Harrisburg, Pennsylvania, 30254', '0989993029', '02408242349', 'DeadraY_Aiello3@gmail.com', '7180246790', 'MSBBank', NULL, '1978-09-01 02:15:00', 'Retta Lord', '1985-01-28 00:20:29', NULL),
('46f514e3-3598-177c-6192-08c864661f9c', 'NV-138', 'Trần Trường Đức', '1954-11-25', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', NULL, '2006-02-26', 'Long An', NULL, '467 SE Hazelwood Loop, 7th FL, Charleston, WV, 26819', '0943040908', NULL, 'Sams@sis.hust.edu.vn', '5132123345', 'BIDV', 'Hà Tĩnh', '1984-12-02 06:23:15', NULL, NULL, 'Kasey Savoy'),
('4729a19e-5a81-6e74-6a92-08c864661f9c', 'NV-181', 'Hồ Trọng Trâm', '1954-04-09', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'F8', '1995-09-15', 'Quảng Bình', 'Nhân viên', '1009 Beachwood Pkwy, Phoenix, Arizona, 27529', '0921974136', '02462460289', 'kwdvu3295@sis.hust.edu.vn', '9228655021', 'MSBBank', 'Hà Tiên', '2018-03-01 11:04:23', 'Cesar Langdon', '1974-05-02 00:26:39', 'Seymour Walls'),
('47405a55-5845-562c-7ddd-867949feb8b5', 'NV-336', 'Nguyễn Trọng Trâm', '1951-03-16', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', NULL, '1970-03-16', 'Đà Nẵng', NULL, '36 South Front Ct, Providence, RI, 12755', '0911152977', NULL, 'Alba29@gmail.com', '1547886303', 'VietinBnak', 'Hà Hồi', '1970-01-01 00:01:15', NULL, NULL, 'Ada Barron'),
('4760d71f-6e2f-5b32-19cb-66948daf6128', 'NV-784', 'Phan Bảo Ánh', '1989-11-12', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '5', '2017-10-20', 'Nghệ An', 'Phó phòng', '40 Bayview Lane, Topeka, Kansas, 52885', '0992878950', '02415093604', 'MalikaZapata@gmail.com', '0007180179', 'TechcomBank', 'Hà Bắc', '1994-04-23 10:47:46', 'Selene Cartwright', '1982-10-22 11:19:05', 'Lorette Ortiz'),
('47ac4f77-1c38-6b23-bcdb-e5d54223c257', 'NV-096', 'Trần Long Thông', NULL, NULL, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '22N', NULL, 'Hà Nội', 'Lễ tân', NULL, NULL, '02497886246', NULL, '0282792997', NULL, 'Hà Hồi', NULL, 'Darius Marr', '1970-01-01 00:15:27', 'Allen Olivo'),
('47f60f67-6087-2a86-abdb-e5d54223c257', 'NV-821', 'Phan Minh Nhật', '1960-11-26', 0, '438598e2-2574-4fc8-2626-978952f080e4', '9', '1979-11-27', 'Nghệ An', 'Thư kí', '1787 Mountain Loop, Salt Lake City, UT, 54836', '0944879817', '02427549508', 'RenaldoBrandt58@gmail.com', '6511080227', 'ShinhanBank', 'Hà Tây', '1970-01-01 01:00:18', 'Pedro Harley', '1977-09-27 00:38:51', 'Donovan Allison'),
('48adb0bd-7040-1241-6e92-08c864661f9c', 'NV-884', 'Hồ Trường Linh', '1967-08-04', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '36', '1972-11-16', 'Quảng Bình', 'Giám đốc', '812 Red Flintwood Way, Boston, MA, 76453', '0990158354', '02459376505', 'CurtisAbernathy815@gmail.com', '2185707607', 'MBBank', 'Hà Tây', '2006-11-02 05:51:15', 'Boyce Covert', '2018-08-04 16:42:00', 'Claud Marion'),
('48c40821-1c72-189a-6792-08c864661f9c', 'NV-931', 'Trần Huỳnh Ánh', '1999-11-12', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '6', '1981-10-24', 'Đà Nẵng', 'Thư kí', '2173 Meadowview Cir, Hartford, CT, 37773', '0913368729', '02431358485', 'WeldonHanna@gmail.com', '6436460136', 'MSBBank', 'Hà Tây', '2006-07-07 12:47:46', 'Brendan Boatwright', '1970-01-01 01:41:19', 'Audie Kearney'),
('4943c139-6a49-4d6e-1663-eeb1d8ed8cef', 'NV-055', 'Uông Đức Linh', '1951-04-05', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '10', '1970-04-05', 'Nghệ An', 'Bảo vệ', '3895 Old Hunting Hill Way, Columbus, OH, 46400', '0977265377', '02456046660', 'Doss223@gmail.com', '2073000238', 'ShinhanBank', 'Hà Bắc', '1970-01-01 00:01:35', 'Adelina Lyon', '1999-01-11 21:19:51', 'Collin Abel'),
('4b5f36b2-71d7-58eb-badb-e5d54223c257', 'NV-419', 'Hồ Ngọc Hiếu', '1951-09-18', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '742GTLZ', '1970-09-18', 'Hưng Yên', 'Trưởng phòng', '3834 Social Lane, Nipper Bldg, Topeka, Kansas, 55400', '0983229364', '02450125715', 'HugoBinkley9@sis.hust.edu.vn', '5933077613', 'ShinhanBank', 'Hà Hồi', '1970-01-01 00:04:21', 'Heriberto Cote', '2020-10-06 21:51:22', 'Adolph Stephens'),
('4c2386b1-57fb-15fa-1063-eeb1d8ed8cef', 'NV-489', 'Trần Trường Giang', NULL, NULL, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'K11Z5WU', NULL, 'Cao Bằng', 'Kế toán', NULL, NULL, '02436792452', NULL, '7992038091', NULL, 'Hà Bắc', NULL, 'Harriet Shelton', '1994-05-28 02:11:55', 'Ada Rapp'),
('4cd4bba1-49ac-6e4c-b4db-e5d54223c257', 'NV-356', 'Nguyễn Trọng Long', '1952-10-30', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '79U04TVUJR', '1971-10-31', 'Cần Thơ', 'Trưởng phòng', '53 Edgewood Hwy, Annapolis, Maryland, 94792', '0984233975', '02455950224', 'Alessandra.Ness42@sis.hust.edu.vn', '0972199530', 'Vietcombank', 'Hà Tiên', '1970-01-01 00:11:09', 'Marcellus Bruno', '1970-01-01 00:00:09', 'Renaldo Norton'),
('4d79d901-1edc-5c5b-0780-e8e2a817c80e', 'NV-302', 'Bùi Đình Hà', '1952-02-04', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'T69A6008V', '1971-02-04', 'Thanh Hóa', 'Tester', '278 Hunting Hill Hwy, Frankfort, KY, 96524', '0992288777', '02483321222', 'DouglassNeville@sis.hust.edu.vn', '9220127083', 'BIDV', 'Hà Tĩnh', '1970-01-01 00:06:40', 'Yaeko Bledsoe', '1970-01-01 00:00:04', 'Carter Wilburn'),
('4d7b21db-2e02-12b7-a9db-e5d54223c257', 'NV-532', 'Phan Đình Thông', '1953-07-30', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '1U61', '1972-07-30', 'Bắc Kạn"', 'Phó phòng', '739 Waterview Hwy, Helena, MT, 64021', '0912549706', '02406633208', 'OldhamP@sis.hust.edu.vn', '6796191056', 'VPBank', 'Hà Nội', '1970-01-01 00:15:42', 'Cierra Neville', '2011-02-12 04:53:16', 'Marine Turley'),
('4e01ca19-178d-1579-9c90-67245e8b283e', 'NV-429', 'Trần Bảo Sơn', '1981-09-25', 0, '438598e2-2574-4fc8-2626-978952f080e4', '1IB1MX42WX560E', '2015-05-30', 'Hà Tĩnh', 'Thư kí', '1206 Old Oak Ct, Des Moines, IA, 82682', '0923883093', '02430893422', 'xjwckfi71@gmail.com', '7592803333', 'BIDV', 'Hà Tiên', '1982-02-10 05:35:57', 'Sandy Abernathy', '1991-08-05 19:46:11', 'Charlotte Morrell'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'NV-542', 'Đỗ Thị Giang', '1988-02-09', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'S', '2007-03-02', 'Hà Nội', 'Dev', '1753 North Church Pkwy, Boise, Idaho, 95705', '0976230036', '02487670349', 'TomSeymour436@gmail.com', '3019996161', 'ACB', 'Hà Bắc', '1978-10-27 18:56:58', 'Treena Lind', '1970-01-01 00:00:08', 'Jackeline Acker'),
('4eceddac-7dc2-38ea-7bdd-867949feb8b5', 'NV-066', 'Đào Bảo Na', NULL, NULL, '34bd2cef-5026-567c-3b71-153b37881afe', '4GA', NULL, 'Đà Nẵng', 'Trưởng phòng', NULL, NULL, '02416647678', NULL, '2355212197', NULL, 'Hà Tĩnh', NULL, 'Leonardo Lockhart', '2019-12-17 07:38:34', 'Abbie Bullard'),
('4f6d1696-757a-42a0-0a80-e8e2a817c80e', 'NV-869', 'Nguyễn Bảo Đức', '1951-03-22', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'I', '1970-03-22', 'Bắc Kạn"', 'Dev', '36 South Sharp Hill Lane, Denver, Colorado, 71583', '0913489070', '02474726695', 'Johansen3@gmail.com', '3174247537', 'Vietcombank', 'Hà Nội', '1970-01-01 00:01:21', 'Nohemi Abraham', '2003-08-12 03:10:26', 'Anissa Pimentel'),
('507bbfcb-3bf9-738b-8cdd-867949feb8b5', 'NV-598', 'Vũ Trọng Hiếu', '1995-01-09', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'R', '2006-06-18', 'Long An', 'Shipper', '2478 White Market Pkwy, Macy''s Building, Atlanta, Georgia, 91158', '0964153092', '02407589520', 'BennettFeldman@gmail.com', '6468104566', 'ACB', 'Hà Nội', '2002-04-15 20:20:11', 'Gayla Ackerman', '1973-03-21 22:44:30', 'Cordie Cooks'),
('50d65da3-631c-5139-9b90-67245e8b283e', 'NV-441', 'Vũ Đình Thông', '1991-07-15', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'U', '2000-04-08', 'Cao Bằng', 'Lễ tân', '1961 Cedar Tree Lane, Keith Building, Columbus, OH, 35475', '0942700339', '02496708822', 'Sergio.Y_Jeter8@gmail.com', NULL, 'BIDV', 'Hà Tĩnh', '1975-09-19 01:59:37', 'Arie Barraza', '1970-01-01 00:41:56', 'Robbie Marquez'),
('511f2482-76be-16cb-84dd-867949feb8b5', 'NV-048', 'Đào Minh Ánh', '1995-03-12', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'W4', '1997-07-24', 'Hải Phòng', 'Shipper', '1018 Riddle Hill Hwy, Little Rock, Arkansas, 40401', '0921714196', '02425985186', 'Rachal_Nutt@sis.hust.edu.vn', '0739274868', 'Vietcombank', 'Hà Nam', '1972-07-29 12:28:34', 'Genevieve Sylvester', '1975-07-21 09:59:51', 'Gary Briones'),
('51b0c827-6de4-34c0-0518-7000f455f3d5', 'NV-493', 'Lê Huỳnh Đức', '1986-11-02', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '0NS94', '1996-07-04', 'Hà Tĩnh', 'Nhân viên', '3032 Fox Hill Circle, Richmond, Virginia, 12477', '0943667018', '02496672705', 'Ojeda@sis.hust.edu.vn', '5140620562', 'MSBBank', 'Hà Nam', '2002-02-26 01:30:44', 'Zachary Selby', '1991-07-29 11:02:13', 'Agatha Slade'),
('52f674bb-7249-7b72-8b32-6a1673ffca7c', 'NV-598', 'Hồ Đức Linh', '1981-03-20', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '4Z2', '1971-10-09', NULL, 'Kế toán', '49 Church Ave, Des Moines, Iowa, 10583', '0985519472', '02489862304', 'Kenney@sis.hust.edu.vn', '0215579821', 'ShinhanBank', NULL, '1976-09-24 15:58:24', 'Voncile Anders', '2009-05-17 23:58:31', NULL),
('52f7159d-5242-1af8-9c7d-e8c757976496', 'NV-747', 'Phan Thị Nhật', '1997-06-08', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '5XVJ114', '2002-07-13', 'Hà Tĩnh', 'Shipper', '33 NW Beachwood Lane, Kearns Building, Saint Paul, Minnesota, 13777', '0944762062', '02419571929', 'GusTomlin283@sis.hust.edu.vn', '2482625925', 'VietinBnak', 'Hà Tây', '2011-06-08 12:57:20', 'Detra Fraley', '2003-09-04 10:57:25', 'Beau Poston'),
('53f6b59c-6af6-4204-6292-08c864661f9c', 'NV-083', 'Vũ Thị Đức', '1991-08-20', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '2M', '2008-12-02', 'Đà Nẵng', 'Giám đốc', '2756 New Hope Highway, Duke Energy Building, Salt Lake City, UT, 95791', '0972847767', '02449843152', 'mwzne9275@gmail.com', '7584597256', 'BIDV', 'Hà Nội', '2004-02-20 19:32:12', 'Erin Sheridan', '1970-01-01 00:00:06', 'Greta Prosser'),
('550c9284-29ba-7fb5-7392-08c864661f9c', 'NV-206', 'Hồ Bảo Trâm', '1977-03-20', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'Q', '1974-01-27', 'Kon Tum', 'Thư kí', '49 Hidden Sharp Hill Pkwy, Richmond, Virginia, 15883', '0928449745', '02401705441', 'Adolph.GNorfleet@gmail.com', '7186194500', 'MSBBank', 'Hà Bắc', '1997-11-02 01:09:56', 'Blake Mora', '1970-01-01 00:01:13', 'Kermit Free'),
('5608f456-3b97-2e05-5d92-08c864661f9c', 'NV-145', 'Hồ Long Phi', '1999-06-26', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'U9', '1970-06-26', NULL, 'Nhân viên', '786 Rock Hill Drive, Augusta, Maine, 44321', '0915176927', '02434150822', 'Sibley72@sis.hust.edu.vn', '6722201253', 'MBBank', NULL, '1977-12-25 17:23:23', 'Eldon Christenson', '1988-07-20 10:37:54', NULL),
('561eb2f7-48b8-58dd-6892-08c864661f9c', 'NV-250', 'Hồ Đức Thịnh', '1956-07-14', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'S3B0P0ZB1', '2002-09-24', 'Cần Thơ', 'Bảo vệ', '78 White Riverview Avenue, 2nd FL, Annapolis, Maryland, 81567', '0964455756', '02423473459', 'Garth.Fowler@gmail.com', NULL, 'ShinhanBank', 'Hà Nam', '2020-03-25 10:20:45', 'Clark Alvarez', '2021-09-02 17:46:43', 'Quentin Abraham'),
('5660d465-6020-48f3-75dd-867949feb8b5', 'NV-664', 'Phạm Đình Trâm', '1997-04-26', 2, '438598e2-2574-4fc8-2626-978952f080e4', 'NM99OGB57T0', '2015-08-23', 'Bắc Kạn"', 'Nhân viên', '3927 North Town Street, Augusta, Maine, 09086', '0987026871', '02413434402', 'Abernathy5@gmail.com', '2990356780', 'MSBBank', 'Hà Tây', '1997-07-15 06:45:57', 'Roland Rowan', '1970-01-01 00:06:55', 'Rolland Watson'),
('56957607-562f-5d6d-1ecb-66948daf6128', 'NV-603', 'Trần Đức Nhật', '1963-06-15', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '48FJ9AGBQ7GY16', '1982-06-15', 'Hải Phòng', 'Phó phòng', '657 Prospect Hill Cir, 1st Floor, Jackson, Mississippi, 86182', '0951750449', '02477195513', 'gajyzvzq6@gmail.com', '3828191057', 'ShinhanBank', 'Hà Tây', '1970-01-01 01:15:49', 'Bradford Finch', '1970-01-01 00:09:11', 'Miesha Goldsmith'),
('56978ca4-3960-6c89-1963-eeb1d8ed8cef', 'NV-887', 'Nguyễn Trọng Thơm', '1952-02-20', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'Z', '1996-03-14', 'Đà Nẵng', 'Thư kí', '152 Mountain Rd, Dover, DE, 59028', '0908088313', '02471358589', 'TerresaRicci8@gmail.com', '1556545001', 'ACB', 'Hà Hồi', '2017-09-26 21:32:55', 'Ivory Phelps', '1975-12-29 19:19:12', 'Stevie Flanders'),
('56b19619-3b4b-5ed3-6d92-08c864661f9c', 'NV-837', 'Vũ Đình Na', '1953-05-21', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '5127929', '1972-05-21', 'Hà Tĩnh', 'Lễ tân', '30 Hope Drive, Annapolis, Maryland, 63087', '0939408996', '02486370956', 'Adamson9@gmail.com', NULL, 'VPBank', 'Hà Nam', '1970-01-01 00:14:32', 'Jamika Hubbard', '1999-02-20 12:44:29', 'Noah Toliver'),
('56ea0e4e-18dc-1b50-6f92-08c864661f9c', 'NV-886', 'Đào Ngọc Thông', NULL, NULL, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'N', NULL, 'Đà Nẵng', 'Thư kí', NULL, NULL, '02467661089', NULL, '7778020417', NULL, 'Hà Đông', NULL, 'Alejandra Prentice', '2018-09-20 07:13:52', 'Grady Riggins'),
('578a959e-1fe6-650e-b8db-e5d54223c257', 'NV-249', 'Hồ Trường Nhật', '1969-09-02', 2, '438598e2-2574-4fc8-2626-978952f080e4', '5', '1988-09-02', NULL, 'Lễ tân', '82 NW Rock Hill St, APT 94, Sacramento, California, 94490', '0944250123', '02442723275', 'AileneAntoine@gmail.com', '0380485096', 'HDBank', NULL, '1970-01-01 01:53:40', 'Fernande Newsom', '1977-10-21 22:19:03', NULL),
('58d8d8a7-140b-5c87-82dd-867949feb8b5', 'NV-767', 'Phan Đình Trâm', '1953-11-19', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'P7W24159Q1SU211G6CWI1ZTT2', '1972-03-18', 'Đà Nẵng', 'Kế toán', '1539 Farmview Street, Bartlett Building, Oklahoma City, OK, 97480', '0973787919', '02463916542', 'sddklaw632@gmail.com', '1104994645', 'BIDV', 'Hà Đông', '1991-04-19 15:13:00', 'Angle Lavigne', '1970-01-01 00:00:22', 'Boyd Thomason'),
('59d19422-6657-452e-a7db-e5d54223c257', 'NV-449', 'Đào Đình Phi', NULL, NULL, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '9D', NULL, 'Đà Nẵng', 'Lễ tân', NULL, NULL, '02477819149', NULL, '1405648859', NULL, 'Hà Tiên', NULL, 'Maynard Brockman', '1987-05-23 21:07:05', 'Kim Desantis'),
('5abcb7aa-4be0-373c-b7db-e5d54223c257', 'NV-307', 'Phan Huỳnh Nhật', NULL, NULL, '438598e2-2574-4fc8-2626-978952f080e4', 'Y8701', NULL, 'Cao Bằng', 'Shipper', NULL, NULL, '02420980434', NULL, '5894815328', NULL, 'Hà Tiên', NULL, 'Felipe Pond', '1970-01-01 00:06:18', 'Judith Ladd'),
('5ae2d70b-201d-3e23-7f32-6a1673ffca7c', 'NV-995', 'Phan Trường Phi', '1983-03-14', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '1F47A95B5BNIL', '2010-10-12', 'Thanh Hóa', 'Bảo vệ', '34 New Waterview Loop, 3rd FL, Carson City, NV, 56781', '0966685612', '02471250132', 'Hook73@gmail.com', '7545669402', 'MBBank', 'Hà Tĩnh', '2013-11-24 06:38:01', 'Darcel Broussard', '1981-12-27 19:05:41', 'Clarinda Acker'),
('5b2fcdf5-2050-7cb2-8f90-67245e8b283e', 'NV-418', 'Phạm Long Ánh', '1978-12-18', 0, '438598e2-2574-4fc8-2626-978952f080e4', 'P', '2018-08-21', 'Nghệ An', 'Phó phòng', '18 2nd Ct, 1st FL, Pierre, SD, 48106', '0963483009', '02442642753', 'Roselia_Carl133@gmail.com', '2786876337', 'AgriBank', 'Hà Tiên', '1985-01-16 23:06:14', 'Fabian Dalton', '1970-01-01 00:10:39', 'Jewel Plummer'),
('5b50bf11-3f80-3d31-9032-6a1673ffca7c', 'NV-476', 'Nguyễn Bảo Hiếu', '1975-01-20', 0, '34bd2cef-5026-567c-3b71-153b37881afe', 'T', '1996-12-29', 'Đà Nẵng', 'Giám đốc', '2183 N Chapel Hill Loop, Nipper Building, Montpelier, VT, 00756', '0952853437', '02438483258', 'StoddardA@gmail.com', '5392065571', 'VPBank', 'Hà Tây', '1981-11-04 05:12:05', 'Adolfo Abbott', '1988-06-27 12:55:59', 'Adah Ornelas'),
('5badffd8-18c8-3f76-6492-08c864661f9c', 'NV-880', 'Nguyễn Ngọc Nhật', '1959-10-26', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '0', '1994-01-07', 'Hưng Yên', 'Giám đốc', '3398 Front Circle, Plaza Building, Dover, DE, 95351', '0930629485', '02492457588', 'JohnsonAbraham@sis.hust.edu.vn', '0829511356', 'Vietcombank', 'Hà Đông', '1993-04-24 00:53:08', 'Merlin Talbott', '1970-01-01 00:10:14', 'Marvella Langston'),
('5c63ba8f-59bb-6d2f-9990-67245e8b283e', 'NV-043', 'Vũ Minh Giang', '1952-02-11', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'AD45', '2012-11-26', 'Đà Nẵng', 'Thư kí', '878 Red Buttonwood Parkway, 3rd FL, Montpelier, VT, 31764', '0946862654', '02459648421', 'Baxter@sis.hust.edu.vn', NULL, 'BIDV', 'Hà Hồi', '2006-07-31 12:18:21', 'Alex Willard', '2001-08-19 05:09:17', 'Cassondra Quintana'),
('5c86869a-6d0c-7cb1-2dcb-66948daf6128', 'NV-311', 'Uông Quốc Linh', NULL, NULL, '438598e2-2574-4fc8-2626-978952f080e4', '89', NULL, 'Kon Tum', 'Kế toán', NULL, NULL, '02480905937', NULL, '8478269943', NULL, 'Hà Tây', NULL, 'Ali Abraham', '2005-09-30 22:45:24', 'Abbie Abney'),
('5d69f482-4df8-2e61-0e80-e8e2a817c80e', 'NV-220', 'Phạm Thị Thơm', '1980-01-06', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '7', '1981-01-25', 'Đà Nẵng', 'Kế toán', '234 NW Deepwood Ave, Topeka, Kansas, 06759', '0925480873', '02436657501', 'BollingK@gmail.com', '4588488594', 'BIDV', 'Hà Bắc', '1976-06-30 17:19:01', 'Terrell Curry', '1970-01-01 00:01:40', 'Jarrett Lujan'),
('60084fec-3509-2779-8432-6a1673ffca7c', 'NV-944', 'Hồ Bảo Linh', '1968-12-19', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '5TX3', '1986-09-04', 'Thanh Hóa', 'Trưởng phòng', '1671 South Brentwood Circle, Judge Building, Concord, NH, 69428', '0938530446', '02468744318', 'MalcolmICulbertson148@gmail.com', '7456316176', 'ACB', 'Hà Tiên', '2013-10-18 23:16:14', 'Brinda Lackey', '1970-01-01 00:00:07', 'Aleisha Story'),
('6081dc00-4df0-5184-9690-67245e8b283e', 'NV-273', 'Lê Minh Sơn', '1990-01-27', 2, '438598e2-2574-4fc8-2626-978952f080e4', NULL, '2003-07-10', 'Hưng Yên', NULL, '89 W Brentwood Highway, Charleston, WV, 79011', '0976650507', NULL, 'SmithW@sis.hust.edu.vn', '5975873239', 'ShinhanBank', 'Hà Tây', '1978-04-24 11:55:27', NULL, NULL, 'Jenny Schulze'),
('6149c4f4-425b-60e0-b3db-e5d54223c257', 'NV-311', 'Đỗ Minh Trâm', '1979-04-18', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '69', '2002-10-12', NULL, 'Thư kí', '189 North Parkwood Lane, MidAmerican Bldg, Albany, NY, 83096', '0996427002', '02490607885', 'AdalineAllen5@gmail.com', '5681784915', 'Vietcombank', NULL, '1993-10-22 02:00:28', 'Nathalie Hollins', '1989-10-24 17:50:51', NULL),
('61a45b9e-55c1-3dbb-f917-7000f455f3d5', 'NV-792', 'Uông Minh Giang', '1996-04-03', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', NULL, '1970-04-23', NULL, NULL, '924 East Church Pkwy, Buhl Building, Sacramento, California, 45033', '0938813927', NULL, 'Gilliland@gmail.com', '9479688942', 'AgriBank', NULL, '2005-05-26 05:27:25', NULL, NULL, NULL),
('61a68ac1-3e74-5149-a290-67245e8b283e', 'NV-327', 'Phạm Bảo Sơn', '1981-03-28', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '77Z', '1988-01-31', 'Cao Bằng', 'Thư kí', '3352 Farmview Dr, Judge Bldg, Dover, Delaware, 77124', '0949875374', '02499927110', 'Bair@sis.hust.edu.vn', '0533404886', 'Vietcombank', 'Hà Tĩnh', '1979-07-04 05:44:29', 'Avery Baggett', '2015-07-31 22:46:15', 'Madie Sales'),
('61de96a0-125e-6f06-9e90-67245e8b283e', 'NV-769', 'Đỗ Minh Thơm', '1983-11-01', 1, '438598e2-2574-4fc8-2626-978952f080e4', '10K56', '1995-11-23', 'Hải Phòng', 'Nhân viên', '1669 Front Dr, 2nd FL, Denver, CO, 70130', '0965292247', '02419650701', 'Robin_Abrams@gmail.com', '9269862732', 'MBBank', 'Hà Tĩnh', '1971-04-12 12:09:30', 'Rita Bair', '1993-06-13 17:36:43', 'Seema Abney'),
('62071e5d-7876-6982-a67d-e8c757976496', 'NV-166', 'Trần Văn Linh', '1966-02-13', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'DE3', '1982-12-01', 'Bắc Giang', 'Lễ tân', '265 Riverview Dr, Columbia, South Carolina, 17579', '0938246225', '02461098956', 'WarnerAntoine@sis.hust.edu.vn', '1839396023', 'ACB', 'Hà Tây', '2012-06-02 12:06:38', 'Cecil Ragan', '1970-01-01 00:01:32', 'Erik Abney'),
('620dbda4-3d7b-6ef2-89dd-867949feb8b5', 'NV-274', 'Bùi Quốc Thơm', '1951-02-24', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '5F5631IF', '1970-02-24', 'Cần Thơ', 'Thư kí', '56 South Monument St, Plaza Building, Juneau, Alaska, 57155', '0994283317', '02487693443', 'Adair@gmail.com', '5444986726', 'BIDV', 'Hà Nam', '1970-01-01 00:00:55', 'Trisha Raney', '2007-04-28 09:04:42', 'Matthew Briseno'),
('6429b0f4-1391-7f32-9390-67245e8b283e', 'NV-277', 'Trần Long Nhật', '1955-03-19', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '31C56ZADG81848Q2', '1984-10-05', 'Hà Tĩnh', 'Shipper', '1664 NW Edgewood Pkwy, Buhl Building, Tallahassee, Florida, 40360', '0945935632', '02417222370', 'nmhqoynb_nauye@gmail.com', '6230845326', 'VPBank', 'Hà Đông', '1973-01-28 17:59:26', 'Ahmed Burkett', '2002-01-11 20:14:41', 'Jeremy Aranda'),
('65a8faaa-15cf-61dc-7092-08c864661f9c', 'NV-252', 'Hồ Huỳnh Sơn', '1951-06-08', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'N', '1970-06-08', 'Hải Phòng', 'Shipper', '981 Old Church Lane, Judge Building, Nashville, Tennessee, 84959', '0912364607', '02485730293', 'AlanaU.Macias7@sis.hust.edu.vn', NULL, 'ShinhanBank', 'Hà Đông', '1970-01-01 00:02:39', 'Mikki Beals', '1998-01-28 23:43:50', 'Beatrice Mena'),
('66e9a5b8-2a02-52f5-85dd-867949feb8b5', 'NV-916', 'Đào Trường Phi', '1963-04-21', 0, '438598e2-2574-4fc8-2626-978952f080e4', 'B', '2008-02-12', 'Hưng Yên', 'Phó phòng', '667 Hidden Hazelwood Ct, Hartford, CT, 70671', '0970452240', '02411702359', 'Alger539@gmail.com', '9111068618', 'HDBank', 'Hà Tiên', '2002-12-24 18:43:14', 'Colton Dowd', '2004-09-25 22:17:21', 'Milford Nevarez'),
('6719e18d-6121-4bee-8c32-6a1673ffca7c', 'NV-284', 'Bùi Thị Đức', '1958-06-30', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '2Q25', '1970-05-17', NULL, 'Tester', '992 White Pine Tree Ct, Olympia, WA, 01569', '0914808903', '02492436050', 'Marci_Acosta@sis.hust.edu.vn', '0307313170', 'VietinBnak', NULL, '1982-12-10 01:56:14', 'Adam Kane', '1970-01-01 00:07:18', NULL),
('6764ab86-6fcc-2757-8032-6a1673ffca7c', 'NV-866', 'Vũ Long Hiếu', '1951-11-09', 2, '34bd2cef-5026-567c-3b71-153b37881afe', 'M', '1970-11-09', NULL, 'Dev', '3984 Ironwood Loop, Santa Fe, NM, 62291', '0955615095', '02412597048', 'Sandie.J_Talbert75@gmail.com', '2045461226', 'BIDV', NULL, '1970-01-01 00:05:13', 'Claude Spellman', '1970-01-01 00:00:10', NULL),
('67b5c284-1c59-4a0a-0580-e8e2a817c80e', 'NV-413', 'Phạm Văn Phi', '1958-04-12', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '8YD5', '1992-08-26', 'Hà Nội', 'Nhân viên', '1758 Red Ski Hill Ln, Dover, DE, 76340', '0975297519', '02471786460', 'LauriAlcorn@gmail.com', '2820912560', 'TechcomBank', 'Hà Hồi', '2010-02-14 18:47:51', 'Elvin Newton', '2020-10-10 06:34:46', 'Jamel Washington'),
('67ef417b-756d-6f15-a27d-e8c757976496', 'NV-691', 'Phạm Minh Phi', '1995-08-09', 1, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'R', '1998-06-09', 'Hà Nội', 'Trưởng phòng', '2409 Glenwood Ave, Calyon Bldg, Harrisburg, Pennsylvania, 11378', '0986877678', '02491806783', 'DebiCagle@gmail.com', '1016215854', 'MBBank', 'Hà Bắc', '2012-02-03 12:41:40', 'Suzanna Sandlin', '1977-08-09 11:43:35', 'Brain Ashworth'),
('68478414-705a-2626-5c92-08c864661f9c', 'NV-540', 'Uông Văn Đức', '1990-06-15', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '77823', '1983-12-29', 'Cần Thơ', 'Dev', '66 East Quailwood Rd, Standard Building, Montgomery, AL, 48135', '0964204721', '02421255843', 'RebeccaCrowe322@gmail.com', NULL, 'MBBank', 'Hà Đông', '1995-06-04 09:07:18', 'Forrest Babb', '2016-06-04 13:45:07', 'Carter Matlock'),
('6916f8cf-1279-16d8-9290-67245e8b283e', 'NV-782', 'Nguyễn Bảo Ánh', '1989-08-17', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '7JZC5', '1992-08-28', 'Long An', 'Shipper', '63 Waterview Ct, Boise, ID, 60661', '0946853537', '02450622578', 'Anderson457@sis.hust.edu.vn', '6285252943', 'Vietcombank', 'Hà Tĩnh', '2007-12-01 22:26:47', 'Xiao Hauser', '1971-02-22 23:25:32', 'Ruben Simpson'),
('696f0f83-27ea-5246-1380-e8e2a817c80e', 'NV-053', 'Uông Minh Sơn', '1982-04-21', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'Q6393C', '2020-12-24', NULL, 'Tester', '270 Flintwood Circle, Jackson, Mississippi, 54934', '0930550069', '02479084161', 'JoslynPuente@gmail.com', '5080681445', 'VietinBnak', NULL, '2004-05-19 23:33:48', 'Willow Abernathy', '2015-05-26 22:40:55', NULL),
('698623e9-1def-6cb3-fa17-7000f455f3d5', 'NV-461', 'Đỗ Đức Ánh', '1952-07-07', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', NULL, '1971-07-08', 'Cao Bằng', NULL, '2392 N Glenwood Hwy, Comcast Building, Phoenix, AZ, 77755', '0916373189', NULL, 'DerickDunham@gmail.com', '1200784633', 'VietinBnak', 'Hà Tĩnh', '1970-01-01 00:09:14', NULL, NULL, 'Brady Street'),
('69cdb3c5-55bc-2a7a-9a7d-e8c757976496', 'NV-902', 'Uông Long Phi', '1962-11-22', 0, '34bd2cef-5026-567c-3b71-153b37881afe', '8L', '2018-11-04', 'Cao Bằng', 'Kế toán', '963 2nd Parkway, Atlanta, Georgia, 68754', '0900435622', '02400406983', 'LuciusBader7@gmail.com', '9262683407', 'MBBank', 'Hà Bắc', '1983-12-25 19:41:22', 'Sherwood Moody', '1970-01-01 01:59:55', 'Lavone Amos'),
('6a4d99cd-242a-6200-7add-867949feb8b5', 'NV-267', 'Đào Trường Linh', '1951-05-22', 2, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'R7T', '1970-05-22', 'Kon Tum', 'Shipper', '1388 Ironwood Ln, Cheyenne, WY, 22475', '0950183432', '02459955498', 'vwmy4817@sis.hust.edu.vn', '2363413804', 'VietinBnak', 'Hà Nội', '1970-01-01 00:02:22', 'Luke Giron', '1989-05-27 00:01:21', 'Eugenia Johansen'),
('6a779fff-7bc4-54f4-b5db-e5d54223c257', 'NV-783', 'Uông Thị Sơn', '1972-10-12', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'V', '2008-07-15', 'Quảng Trị', 'Thư kí', '339 NW Rushwood Blvd, Bartlett Building, Providence, RI, 15507', '0915686751', '02426943508', 'AlexanderWilley@gmail.com', '3509253900', 'ShinhanBank', 'Hà Bắc', '1972-08-13 11:54:35', 'Doloris Matthews', '1997-10-07 00:34:27', 'Lavette Theriault'),
('6af6ef19-44ef-22a6-0118-7000f455f3d5', 'NV-390', 'Phan Long Na', '1961-03-22', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '166J5HKT', '1979-06-24', 'Cần Thơ', 'Trưởng phòng', '568 West Rock Hill Highway, Lansing, MI, 33266', '0929980101', '02486330818', 'Brinda_Maddox4@gmail.com', '7712229592', 'TechcomBank', 'Hà Nam', '2001-10-02 14:29:46', 'Rodger Loveless', '1970-01-01 00:01:27', 'Ali Fuchs'),
('6c97b353-5d7d-4095-1dcb-66948daf6128', 'NV-953', 'Uông Huỳnh Hiếu', '1986-05-07', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', '78', '1977-06-16', 'Hà Nội', 'Dev', '3674 NW Rockwood Loop, Kearns Building, Oklahoma City, OK, 75766', '0903302714', '02466078126', 'ShakitaFerrara48@sis.hust.edu.vn', '3931256416', 'VietinBnak', 'Hà Tĩnh', '2007-06-26 19:59:28', 'Ariane Omalley', '1970-01-01 00:00:08', 'Shawn Deaton'),
('6de8272b-7b3b-319f-8a32-6a1673ffca7c', 'NV-307', 'Nguyễn Bảo Trâm', '1977-06-13', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'S4', '1994-02-24', 'Nghệ An', 'Phó phòng', '2959 1st Blvd, Trenton, New Jersey, 30840', '0946831966', '02451764264', 'Knott@sis.hust.edu.vn', '6907591497', 'MBBank', 'Hà Tây', '1998-10-29 17:29:26', 'Charise Cooks', '1970-01-01 00:00:23', 'Valery Zaragoza'),
('6f2475a8-1ff5-13e7-0680-e8e2a817c80e', 'NV-043', 'Lê Thị Ánh', '1984-07-08', 0, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'Y', '1982-05-20', 'Đà Nẵng', 'Nhân viên', '36 Sharp Hill Cir, Penobscot Building, Providence, Rhode Island, 61033', '0918539460', '02442120180', 'RonniWolford@gmail.com', '4800462723', 'ACB', 'Hà Tiên', '1978-09-30 20:59:55', 'Carlton Baptiste', '1970-01-01 00:00:02', 'Eddy Snodgrass'),
('6f9b639b-6124-3874-a87d-e8c757976496', 'NV-660', 'Nguyễn Trọng Hà', '1964-12-27', 2, '438598e2-2574-4fc8-2626-978952f080e4', 'A', '1985-07-06', NULL, 'Dev', '3564 New Highland Way, Plaza Building, Raleigh, North Carolina, 37872', '0913225139', '02442628902', 'Vinson168@gmail.com', '1073115683', 'Vietcombank', NULL, '1974-07-22 11:58:44', 'Loris Casteel', '1970-01-01 00:12:58', NULL),
('70253ec7-2e38-67a9-b1db-e5d54223c257', 'NV-973', 'Trần Bảo Phi', '1984-03-03', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'NXVP', '1991-02-27', 'Long An', 'Dev', '68 Riverview Lane, Little Rock, Arkansas, 08092', '0908391296', '02471131796', 'Ramsey6@gmail.com', '2484370444', 'TechcomBank', 'Hà Nam', '2017-01-12 09:46:14', 'Julia Kopp', '1970-01-01 00:09:31', 'Daron Lowery'),
('7050d79b-6948-3c66-1fcb-66948daf6128', 'NV-309', 'Hồ Trọng Na', '1952-08-01', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', NULL, '1971-08-02', 'Đà Nẵng', NULL, '348 West Flintwood Drive, Albany, NY, 16608', '0975965908', NULL, 'ryme620@gmail.com', '9218734699', 'MSBBank', 'Hà Nam', '1970-01-01 00:09:39', NULL, NULL, 'Theola Addison'),
('70af83de-413e-63ef-6592-08c864661f9c', 'NV-286', 'Đỗ Đình Thơm', '1977-09-21', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'N5LWNPNA', '1995-04-13', 'Đà Nẵng', 'Lễ tân', '95 Hope Pkwy, Oklahoma City, OK, 43843', '0927729500', '02451441040', 'Dallas.Ackerman@gmail.com', '9738333967', 'AgriBank', 'Hà Nam', '1977-06-22 02:21:47', 'Patsy Blaine', '1982-03-25 07:49:18', 'Martin Carpenter'),
('70d5acf3-2d43-7ebb-9a90-67245e8b283e', 'NV-785', 'Bùi Ngọc Linh', '1953-03-02', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', NULL, '1972-03-02', 'Quảng Bình', NULL, '93 Red Hunting Hill Loop, Jefferson City, MO, 43405', '0907838024', NULL, 'Correia663@gmail.com', '9303991270', 'ACB', 'Hà Đông', '1970-01-01 00:13:12', NULL, NULL, 'Joey Seiler'),
('7136099c-206b-1466-81dd-867949feb8b5', 'NV-753', 'Phan Thị Ánh', '1951-02-20', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '2S1', '1970-02-20', 'Thanh Hóa', 'Trưởng phòng', '1225 Old Church Pkwy, 257 Towers Bldg, Pierre, South Dakota, 34732', '0956384709', '02452968860', 'Hester@gmail.com', NULL, 'MSBBank', 'Hà Nam', '1970-01-01 00:00:51', 'Abel Abreu', '1970-01-01 02:13:50', 'Bella Crabtree'),
('71c459c3-508d-1245-b6db-e5d54223c257', 'NV-470', 'Đỗ Quốc Hiếu', '1956-01-15', 1, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'B', '2015-06-13', NULL, 'Kế toán', '3012 East Ski Hill Lane, Indianapolis, Indiana, 14522', '0950626819', '02428062550', 'JohnieBullard69@sis.hust.edu.vn', '6627721959', 'TechcomBank', NULL, '2007-02-21 21:49:48', 'Johanna Fuqua', '2009-07-03 09:12:23', NULL),
('725df9dc-25c1-58eb-a490-67245e8b283e', 'NV-563', 'Đỗ Bảo Đức', NULL, NULL, '438598e2-2574-4fc8-2626-978952f080e4', '3', NULL, 'Đà Nẵng', 'Dev', NULL, NULL, '02416118459', NULL, NULL, NULL, 'Hà Đông', NULL, 'Jessi Alba', '2016-02-06 17:25:54', 'Delaine Bowen'),
('72ce912f-6015-2e14-fb17-7000f455f3d5', 'NV-426', 'Đỗ Trường Nhật', '1976-08-22', 1, '34bd2cef-5026-567c-3b71-153b37881afe', 'JU', '1982-05-24', 'Nghệ An', 'Tester', '35 NW Rushwood Parkway, Albany, New York, 58177', '0913849507', '02406464333', 'Alethea_Joiner687@sis.hust.edu.vn', '1564308550', 'VietinBnak', 'Hà Nội', '2002-06-20 21:53:33', 'Jeramy Andrus', '1990-09-11 11:41:00', 'Azalee Wang'),
('7325f44f-127c-240c-afdb-e5d54223c257', 'NV-036', 'Phan Minh Đức', '1982-04-16', 2, '674934cc-42cf-20cf-1d4a-aea48a10ed18', 'C', '2013-05-17', 'Cao Bằng', 'Shipper', '2315 East Mount Ct, Victor Executive Bldg, Jackson, Mississippi, 26804', '0954973998', '02436861066', 'Jacques9@gmail.com', '9065231595', 'TechcomBank', 'Hà Tây', '1989-11-01 00:34:08', 'Marjorie Ouellette', '1970-01-01 00:14:47', 'Augustus Barnette'),
('73feb9c0-5258-209c-1280-e8e2a817c80e', 'NV-459', 'Vũ Bảo Ánh', '1952-06-24', 2, '438598e2-2574-4fc8-2626-978952f080e4', 'C0', '1999-11-21', NULL, 'Lễ tân', '2952 Beachwood Drive, Juneau, AK, 68946', '0904275049', '02415928031', 'MaryjaneGlaser@gmail.com', '1700089890', 'Vietcombank', NULL, '2014-04-13 15:15:55', 'Nickolas Dow', '1970-01-01 00:00:09', NULL),
('74017ba6-559b-3426-8532-6a1673ffca7c', 'NV-801', 'Bùi Văn Phi', NULL, NULL, '674934cc-42cf-20cf-1d4a-aea48a10ed18', '56Q810VMJZY8', NULL, 'Thanh Hóa', 'Nhân viên', NULL, NULL, '02451706370', NULL, '3348465477', NULL, 'Hà Đông', NULL, 'Reina Ramirez', '1970-01-01 00:00:09', 'Chiquita Headrick'),
('756ac66d-5ca5-79ff-b9db-e5d54223c257', 'NV-943', 'Lê Trường Ánh', '1966-03-18', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '79SF', '2009-10-18', 'Quảng Trị', 'Nhân viên', '3246 North Fox Hill Ave, Augusta, ME, 35712', '0930993183', '02414875823', 'Adela_Cobb@gmail.com', '4713528576', 'MBBank', 'Hà Bắc', '1984-06-16 06:19:17', 'Janine Adam', '1970-01-01 00:01:04', 'Elouise Jarrett'),
('758f86f1-3af9-68b9-1763-eeb1d8ed8cef', 'NV-381', 'Nguyễn Bảo Sơn', '1993-08-10', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '6', '1973-08-17', 'Quảng Bình', 'Kế toán', '419 Edgewood Cir, Enquirer Bldg, Providence, Rhode Island, 55488', '0920350984', '02406340073', 'Rodgers27@gmail.com', '0781089242', 'Vietcombank', 'Hà Tĩnh', '2018-12-19 05:13:30', 'Clarinda Albers', '2015-07-31 23:00:10', 'Lawrence Stowe'),
('75fcbf6d-4e84-4cc4-9f90-67245e8b283e', 'NV-659', 'Đỗ Văn Ánh', '1956-01-19', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'R7', '2018-10-06', 'Cần Thơ', 'Bảo vệ', '1955 Riverview Lane, Indianapolis, Indiana, 03348', '0951950233', '02461531991', 'CasandraRoyal@sis.hust.edu.vn', '7476003932', 'HDBank', 'Hà Nội', '2004-02-11 23:45:57', 'Collin England', '1994-03-30 20:14:23', 'Ozie Abbott'),
('7623d42f-35f4-1ce5-987d-e8c757976496', 'NV-881', 'Hồ Minh Sơn', '1994-01-26', 1, '438598e2-2574-4fc8-2626-978952f080e4', '10', '2005-05-12', 'Hà Nội', 'Dev', '875 Stonewood Pkwy, Carson City, Nevada, 72024', '0924735117', '02435786542', 'ikzv7@sis.hust.edu.vn', '4275445501', 'Vietcombank', 'Hà Tĩnh', '1988-06-22 15:27:39', 'Abel Woodward', '1970-01-01 02:25:46', 'Darrick Cardoza'),
('767111e6-3dbc-615a-0880-e8e2a817c80e', 'NV-690', 'Phan Minh Thơm', '1979-08-25', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', 'S', '1988-09-29', NULL, 'Dev', '979 Oak Court, Frankfort, KY, 12341', '0984034158', '02499068480', 'Abraham@gmail.com', '1936558854', 'ShinhanBank', NULL, '1982-08-16 13:22:08', 'Adam Dove', '1970-01-01 00:43:29', NULL),
('7686595d-16d5-33b3-0080-e8e2a817c80e', 'NV-786', 'Đào Ngọc Hiếu', '1962-02-28', 0, '438598e2-2574-4fc8-2626-978952f080e4', '3', '1994-02-18', 'Hải Phòng', 'Nhân viên', '2989 East Pine Tree Road, Topeka, KS, 16758', '0926437957', '02477695257', 'Parson@gmail.com', '2284567808', 'Vietcombank', 'Hà Nam', '1977-06-11 22:33:25', 'Carroll Binder', '1983-01-15 23:21:53', 'Kendrick Naranjo'),
('768f8e64-7d10-20c9-967d-e8c757976496', 'NV-435', 'Nguyễn Trọng Thơm', '1960-02-23', 0, '43a6bdf5-1b6b-451b-3695-2c566fa88632', NULL, '2010-03-13', NULL, NULL, '1955 Front Road, Madison, WI, 37006', '0952445875', NULL, 'zzpqybc5243@gmail.com', '5234935930', 'MBBank', NULL, '2015-06-11 19:50:44', NULL, NULL, NULL),
('771e3dd1-42bb-2339-acdb-e5d54223c257', 'NV-268', 'Phạm Đức Phi', '1955-10-30', 1, '34bd2cef-5026-567c-3b71-153b37881afe', 'M66K86', '1996-08-15', 'Quảng Trị', 'Trưởng phòng', '31 SE Stonewood Lane, Annapolis, Maryland, 85286', '0976032514', '02429230629', 'Bob.Y.Copley5@gmail.com', '6929606442', 'ShinhanBank', 'Hà Bắc', '1983-04-16 03:41:56', 'Darrin Downey', '1970-01-01 00:10:02', 'Robbie Canty'),
('773acde0-4741-351b-6992-08c864661f9c', 'NV-020', 'Trần Đức Thơm', '1968-06-19', 2, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '2OK', '2019-05-15', 'Cần Thơ', 'Bảo vệ', '3997 White Chapel Hill Court, Saint Paul, MN, 34890', '0927496112', '02499927307', 'Marks@sis.hust.edu.vn', '6592790829', 'HDBank', 'Hà Nội', '1982-03-22 00:19:29', 'Jim Hutto', '2013-04-06 17:58:51', 'Corey Turley'),
('791b9e6b-6010-1e33-b0db-e5d54223c257', 'NV-519', 'Phan Đức Linh', '1951-01-10', 1, '438598e2-2574-4fc8-2626-978952f080e4', '8098W937ISU6', '1970-01-10', 'Cao Bằng', 'Lễ tân', '114 4th Blvd, Charleston, West Virginia, 84421', '0998091615', '02436116564', 'Marva.Landis@gmail.com', '1046828524', 'Vietcombank', 'Hà Nội', '1970-01-01 00:00:10', 'Candelaria Padgett', '1991-09-02 01:15:07', 'Mitchell Tanner'),
('79fa8253-391f-4864-b2db-e5d54223c257', 'NV-585', 'Đỗ Đức Nhân', '1965-07-20', 2, '34bd2cef-5026-567c-3b71-153b37881afe', NULL, '2018-08-29', 'Cao Bằng', NULL, '45 NE Brentwood Pkwy, Duke Energy Building, Bismarck, North Dakota, 61210', '0954662135', NULL, 'Acker@gmail.com', '1838458877', 'TechcomBank', 'Hà Bắc', '2013-09-06 15:40:51', NULL, '2021-09-01 17:48:39', 'Bob Whitlow'),
('7abe18db-2b8a-5fcb-aedb-e5d54223c257', 'NV-306', 'Trần Quốc Hà', '1978-02-22', 1, '438598e2-2574-4fc8-2626-978952f080e4', 'W', '1997-02-22', 'Cao Bằng', 'Nhân viên', '30 51th Road, Equitable Building, Trenton, New Jersey, 66590', '0971785014', '02460705561', 'PollackL324@sis.hust.edu.vn', NULL, 'MSBBank', 'Hà Tĩnh', '1970-01-01 02:45:15', 'Heriberto Purdy', '1970-01-01 00:01:09', 'Gilda Abney'),
('7bec5682-21c4-666f-a8db-e5d54223c257', 'NV-643', 'Uông Đức Thắng', '1951-01-01', 2, '43a6bdf5-1b6b-451b-3695-2c566fa88632', 'H9A', '1970-01-01', 'Kon Tum', 'Thư kí', '3215 Beachwood Highway, Lincoln, Nebraska, 38238', '0945162782', '02471962253', 'Keefe28@gmail.com', '4539976947', 'VietinBnak', 'Hà Tĩnh', '1970-01-01 00:00:01', 'Augustine Corbin', '1970-01-01 00:01:06', 'Clemente Craddock'),
('7c6a2a90-6ea1-133c-7492-08c864661f9c', 'NV-405', 'Hồ Bảo Phi', '1978-03-28', 1, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '2', '1996-04-28', 'Nghệ An', 'Dev', '182 East Rose Hill Court, Suite 119, Pierre, South Dakota, 84486', '0940311315', '02494743773', 'Kathaleen.Aponte7@gmail.com', '6583107204', 'VPBank', 'Hà Tiên', '1973-05-27 21:48:02', 'Lindsay Cormier', '1985-01-24 00:53:56', 'Ross Huntley'),
('7d663944-7eb7-7c68-8add-867949feb8b5', 'NV-004', 'Phan Bảo Thông', '1984-05-31', 2, '438598e2-2574-4fc8-2626-978952f080e4', '8VP2', '2020-05-07', 'Đà Nẵng', 'Dev', '2980 South Hunting Hill Blvd, Des Moines, IA, 34634', '0915806278', '02462063433', 'Laird@sis.hust.edu.vn', '0846158358', 'TechcomBank', 'Hà Bắc', '1985-03-08 08:40:39', 'Hunter Tabor', '1978-01-22 17:11:36', 'Abigail Mcgrew'),
('7dbdf5fd-6a92-497b-0c80-e8e2a817c80e', 'NV-323', 'Uông Huỳnh Giang', '1971-10-01', 1, '34bd2cef-5026-567c-3b71-153b37881afe', '3', '1998-04-28', 'Thanh Hóa', 'Nhân viên', '15 New Quailwood Circle, Guardian Building, Saint Paul, Minnesota, 75621', '0919450330', '02454037301', 'Chastain785@gmail.com', '3620241736', 'AgriBank', 'Hà Nội', '1980-02-11 16:56:33', 'Shalonda Hamm', '2014-02-01 19:55:52', 'Cordell Addison'),
('7e8f50b2-5100-74d8-0480-e8e2a817c80e', 'NV-119', 'Lê Đình Thông', '1975-06-14', 0, '34bd2cef-5026-567c-3b71-153b37881afe', 'IN5N', '2003-03-31', 'Bắc Giang', 'Shipper', '218 Riddle Hill Lane, Austin, Texas, 74487', '0931117679', '02431259227', 'TraciCloud@sis.hust.edu.vn', '9421887459', 'ACB', 'Hà Hồi', '2003-04-12 05:56:05', 'Carolann Cosgrove', '2006-01-10 05:12:02', 'Christeen Oconnor'),
('7f3d5027-1858-6752-1080-e8e2a817c80e', 'NV-669', 'Bùi Ngọc Ánh', '1987-02-06', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', '3', '1997-02-18', 'Hà Nội', 'Bảo vệ', '2661 Quailwood Ln, 3rd Floor, Lincoln, Nebraska, 43187', '0938015440', '02406147010', 'qebyo6@sis.hust.edu.vn', '4058999062', 'ShinhanBank', 'Hà Tĩnh', '1995-06-19 01:19:08', 'Christena Ruth', '1970-08-09 17:20:58', 'Anderson Farrington'),
('7f4552ee-20f2-2f82-9890-67245e8b283e', 'NV-344', 'Hồ Minh Hiếu', '1981-12-19', 0, '64a59a25-2488-54b0-f6b4-c8af08a50cbf', NULL, '2003-02-12', 'Quảng Bình', NULL, '1647 Brentwood Blvd, APT 348, Salem, OR, 60219', '0950714422', NULL, 'Finney186@gmail.com', NULL, 'MBBank', 'Hà Tiên', '2020-03-20 22:53:24', NULL, '2021-09-03 15:59:30', 'Ahmed Abernathy'),
('7f609b3d-31d7-548b-0318-7000f455f3d5', 'NV-155', 'Đỗ Ngọc Hà', '1952-12-20', 2, '34bd2cef-5026-567c-3b71-153b37881afe', '7312E', '1971-12-21', 'Thanh Hóa', 'Phó phòng', '1554 Mountain Highway, Superior Bldg, Nashville, Tennessee, 10409', '0991269774', '02463820082', 'AntioneAbreu@gmail.com', '8324127083', 'BIDV', 'Hà Đông', '1970-01-01 00:12:00', 'Nicky Hubert', '1970-01-01 00:07:53', 'Alexander Abreu'),
('7f662b42-535c-433b-6c92-08c864661f9c', 'NV-200', 'Vũ Thị Sơn', '1958-02-09', 2, '34bd2cef-5026-567c-3b71-153b37881afe', 'JK', '1985-07-01', NULL, 'Phó phòng', '2314 E Pine Tree Blvd, 6th FL, Augusta, ME, 97333', '0912224804', '02478345283', 'Candis.Randle@gmail.com', '2493395400', 'ShinhanBank', NULL, '2014-08-24 18:40:38', 'Zella Merriman', '2020-06-06 09:59:32', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;